return {
	{
		id = "bleeding",
		isStack = true,
		name = strings.bleeding,
		tagList = { "debuff", "physic" },
		damage = 5,
		durationInRound = 2,
		iconFile = "bleeding",
	},
	{
		id = "bleeding2",
		isStack = true,
		name = strings.bleeding,
		tagList = { "debuff", "physic" },
		damage = 40,
		durationInRound = 2,
		iconFile = "bleeding",
	},
	{
		id = "burning",
		isStack = true,
		iconFile = "fire",
		damage = 5,
		tagList = { "debuff", "fire_tag" },
		durationInRound = 2,
	},
	{
		id = "burning2",
		isStack = true,
		name = strings.battleEffect.burning,
		tagList = { "debuff", "fire_tag" },
		damage = 20,
		durationInRound = 2,
		iconFile = "fire",
	},
	{
		id = "burning3",
		isStack = true,
		name = strings.battleEffect.burning,
		tagList = { "debuff", "fire_tag" },
		damage = 100,
		durationInRound = 2,
		iconFile = "fire",
	},
	{
		id = "burning4",
		isStack = true,
		name = strings.battleEffect.burning,
		tagList = { "debuff", "fire_tag" },
		damage = 200,
		durationInRound = 2,
		iconFile = "fire",
	},
	{
		id = "acid",
		isStack = true,
		name = strings.resist.acid,
		tagList = { "debuff", "acid" },
		damage = 20,
		durationInRound = 3,
		iconFile = "acid",
	},
	{
		id = "poison",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 5,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "poison_weapon",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 5,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "poison_weapon2",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 10,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "poison_weapon3",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 20,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "poison_weapon4",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 50,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "poison_weapon5",
		isStack = true,
		name = strings.poison.name,
		tagList = { "debuff", "poison" },
		damage = 150,
		durationInRound = 2,
		iconFile = "poison",
	},
	{
		id = "freezed",
		tagList = { "debuff" },
		iconFile = "freezed",
		name = strings.freezed,
		effect = {
			isStun = true,
		},
		durationInRound = 1,
	},
	{
		id = "slowed",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed,
		effect = {
			speed = -2,
		},
		durationInRound = 3,
	},
	{
		id = "bitume_slowed",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed,
		effect = {
			speed = -1,
		},
		durationInRound = 3,
	},
	{
		id = "snow_slowed",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed_snow,
		effect = {
			speed = -1,
		},
		durationInRound = 2,
	},
	{
		id = "snow_speed",
		tagList = { "buff" },
		iconFile = "speed",
		name = strings.speed_snow,
		effect = {
			speed = 1,
		},
		durationInRound = 2,
	},
	{
		id = "stuned",
		tagList = { "debuff" },
		iconFile = "stuned",
		name = strings.stuned,
		effect = {
			isStun = true,
		},
		durationInRound = 1,
	},
	{
		id = "inaction",
		tagList = { "debuff" },
		iconFile = "stuned",
		name = strings.inaction,
		effect = {
			isStun = true,
		},
		durationInRound = 1,
	},
	{
		id = "blindness",
		tagList = { "debuff" },
		iconFile = "blindness",
		name = strings.blindness,
		effect = {
			missChance = 0.9,
		},
		durationInRound = 3,
	},
	{
		id = "trap",
		tagList = { "debuff" },
		iconFile = "trap",
		isOnlyText = true,
		text = strings.blockMove,
		effect = {
			speed = -10,
		},
		durationInRound = 1,
	},
	{
		id = "stake_pit",
		tagList = { "debuff" },
		name = strings.battleEffect.trap,
		text = strings.blockMove,
		durationInRound = 3,
		damage = 10,
		effect = {
			speed = -10,
		},
		iconFile = "trap",
	},
	{
		id = "web",
		tagList = { "debuff" },
		name = strings.battleEffect.trap,
		isOnlyText = true,
		text = strings.blockMove,
		iconFile = "trap",
		effect = {
			speed = -10,
		},
		durationInRound = 2,
	},
	{
		id = "angry_bees",
		isStack = true,
		iconFile = "bee",
		damage = 10,
		tagList = { "debuff" },
		durationInRound = 3,
	},
	{
		id = "raven_distract",
		tagList = { "debuff" },
		iconFile = "stuned",
		name = strings.distraction,
		effect = {
			isStun = true,
		},
		durationInRound = 1,
	},
	{
		id = "raven_blindness",
		tagList = { "debuff" },
		iconFile = "blindness",
		name = strings.blindness,
		effect = {
			missChance = 0.9,
		},
		durationInRound = 1,
	},
	{
		id = "wolf_hold",
		tagList = { "debuff" },
		name = strings.immobilization,
		isOnlyText = true,
		text = strings.blockMove,
		iconFile = "trap",
		effect = {
			speed = -10,
		},
		durationInRound = 1,
	},
	{
		id = "wolf_provoke",
		tagList = { "debuff" },
		name = strings.provoke,
		text = strings.provoke_text,
		iconFile = "provoke",
		effect = {
			aggro = 100,
		},
		durationInRound = 1,
	},
	{
		id = "polar_fox_debuff",
		tagList = { "debuff" },
		iconFile = "down",
		name = strings.polar_fox_debuff,
		effect = {
			selfDamageMult = 0.25,
			dodgeChance = -0.25,
		},
		durationInRound = 2,
	},
	{
		id = "charm",
		tagList = { "debuff" },
		isAddChanceForWeak = true,
		isCharmEnemy = true,
		name = strings.charm,
		text = strings.charm_text,
		iconFile = "charm",
		durationInRound = 2,
	},
	{
		id = "charm_dollar",
		tagList = { "debuff" },
		isAddChanceForWeak = true,
		isCharmEnemy = true,
		name = strings.charm_dollar,
		text = strings.charm_text,
		iconFile = "charm_dollar",
		durationInRound = 2,
	},
	{
		id = "debuff_resist_vam",
		tagList = { "debuff" },
		iconFile = "down",
		name = strings.pray_mark,
		resistTable = {
			vampire = -0.2,
		},
		durationInRound = 99,
	},
	{
		id = "fear",
		tagList = { "debuff" },
		iconFile = "pentagram",
		name = strings.fear,
		effect = {
			missChance = 0.25,
		},
		durationInRound = 2,
	},
	{
		id = "luck",
		tagList = { "buff" },
		iconFile = "luck",
		name = strings.luck,
		effect = {
			attackChance = 0.25,
		},
		durationInRound = 2,
	},
	{
		id = "curse",
		tagList = { "debuff" },
		iconFile = "pentagram",
		name = strings.curse,
		effect = {
			selfDamageMult = 0.2,
		},
		durationInRound = 5,
	},
	{
		id = "possessed",
		isStack = true,
		name = strings.possession,
		tagList = { "buff" },
		iconFile = "possession",
		addAfterDeath = {
			spawnUnits = { "poltergeist1" },
		},
		effect = {
			damageMult = 0.3,
		},
	},
	{
		id = "deadman_touch",
		isStack = true,
		name = strings.deadman_touch,
		tagList = { "debuff" },
		iconFile = "pentagram",
		stackLimit = 9,
		effect = {
			damageMult = -0.1,
		},
		durationInRound = 2,
	},
	{
		id = "vulnerability",
		tagList = { "debuff" },
		iconFile = "down",
		name = strings.vulnerability,
		effect = {
			selfDamageMult = 0.25,
		},
		durationInRound = 2,
	},
	{
		id = "star_blindness",
		tagList = { "debuff" },
		iconFile = "blindness",
		name = strings.blindness,
		effect = {
			missChance = 0.25,
		},
		durationInRound = 2,
	},
	{
		id = "star_blindness2",
		tagList = { "debuff" },
		iconFile = "blindness",
		name = strings.blindness,
		effect = {
			missChance = 0.5,
			dodgeChance = -0.5,
		},
		durationInRound = 2,
	},
	{
		id = "microbes",
		isStack = true,
		name = strings.timer,
		tagList = { "debuff", "physic" },
		damage = 5,
		durationInRound = 3,
		iconFile = "provoke",
	},
	{
		id = "sweets_buff_dmg",
		isStack = true,
		name = strings.sweets_buff,
		text = strings.gift_strength,
		tagList = { "buff" },
		iconFile = "energy",
		addAfterDeath = {
			weapon = {
				id = "buff_ghost_damage",
				isNearestUnit = true,
			},
		},
		durationInRound = 2,
	},
	{
		id = "sweets_buff_resist",
		isStack = true,
		name = strings.sweets_buff,
		text = strings.gift_stamina,
		tagList = { "buff" },
		iconFile = "energy",
		addAfterDeath = {
			weapon = {
				id = "buff_snowman_resist",
				isNearestUnit = true,
			},
		},
		durationInRound = 2,
	},
	{
		id = "sweets_buff_speed",
		isStack = true,
		name = strings.sweets_buff,
		text = strings.gift_speed,
		tagList = { "buff" },
		iconFile = "energy",
		addAfterDeath = {
			weapon = {
				id = "buff_ghost_speed",
				isNearestUnit = true,
			},
		},
		durationInRound = 2,
	},
	{
		id = "resistance",
		isStack = true,
		name = strings.damage_resist,
		tagList = { "buff" },
		iconFile = "shield_full",
		effect = {
			selfDamageMult = -0.15,
		},
		durationInRound = 2,
	},
	{
		id = "bee_mother_wax",
		tagList = { "debuff" },
		name = strings.battleEffect.trap,
		isOnlyText = true,
		text = strings.blockMove,
		iconFile = "trap",
		effect = {
			speed = -20,
		},
		durationInRound = 1,
	},
	{
		id = "sleep",
		tagList = { "debuff" },
		iconFile = "sleep",
		name = strings.stuned,
		effect = {
			isStun = true,
		},
		durationInRound = 99,
	},
	{
		id = "slowed_madman_big",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed,
		effect = {
			speed = -1,
		},
		durationInRound = 1,
	},
	{
		id = "slowed_queen",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed,
		effect = {
			speed = -2,
		},
		durationInRound = 2,
	},
	{
		id = "spore_infection",
		isStack = true,
		name = strings.spore.name,
		tagList = { "debuff", "spore" },
		iconFile = "poison",
		durationInRound = 3,
		effect = {
			selfDamageMult = 0.1,
		},
	},
	{
		id = "red_flower_infection",
		tagList = { "debuff", "spore" },
		iconFile = "poison",
		name = strings.spore.name,
		durationInRound = 3,
		effect = {
			damageMult = -0.8,
			missChance = 0.8,
		},
	},
	{
		id = "slowed_turret",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.slowed,
		effect = {
			speed = -1,
		},
		durationInRound = 2,
	},
	{
		id = "electro_stunned",
		tagList = { "debuff" },
		iconFile = "stuned",
		name = strings.stuned,
		damage = 250,
		effect = {
			isStun = true,
		},
		durationInRound = 1,
	},
	{
		id = "worm_infection",
		tagList = { "debuff", "spore" },
		name = strings.worm_infection.name,
		text = strings.worm_infection.description,
		addAfterDeath = {
			spawnQuantity = 3,
			spawnUnits = { "corpse_worm_little1" },
		},
		iconFile = "worm",
	},
	{
		id = "spore_shield",
		isStack = true,
		name = strings.spore_bubble.name,
		text = strings.spore_bubble.description,
		tagList = { "buff", "spore" },
		iconFile = "poison_shield",
		resistTable = {
			spore = 0.5,
		},
		durationInRound = 1,
	},
	{
		id = "dodge_debuff",
		isStack = true,
		name = strings.dodge_debuff,
		tagList = { "debuff" },
		iconFile = "down",
		effect = {
			dodgeChance = -0.7,
		},
		durationInRound = 2,
	},
	{
		id = "resist_range_debuff",
		isStack = true,
		name = strings.resist_broken_range.name,
		text = strings.resist_broken_range.description,
		tagList = { "debuff" },
		iconFile = "down",
		resistTable = {
			explosive = -0.4,
			firearm_tag = -0.4,
			crossbow_tag = -0.4,
		},
		durationInRound = 3,
	},
	{
		id = "spore_regen",
		isStack = true,
		name = strings.perk_regen,
		tagList = { "buff", "spore" },
		iconFile = "plus",
		healing = 500,
		durationInRound = 2,
	},
	{
		id = "speed_mad",
		tagList = { "buff" },
		iconFile = "speed",
		name = strings.encouraged,
		effect = {
			speed = 1,
		},
		durationInRound = 2,
	},
	{
		id = "buff_mad",
		isStack = true,
		name = strings.encouraged,
		tagList = { "buff" },
		effect = {
			damageMult = 0.1,
		},
		iconFile = "sword",
	},
	{
		id = "slowed_endless",
		tagList = { "debuff" },
		iconFile = "leg",
		effect = {
			speed = -1,
		},
		name = strings.slowed,
	},
	{
		id = "buff_damage",
		isStack = true,
		name = strings.gift_strength,
		tagList = { "buff" },
		effect = {
			damageMult = 1,
		},
		iconFile = "sword",
	},
	{
		id = "buff_speed",
		isStack = true,
		name = strings.gift_speed,
		tagList = { "buff" },
		effect = {
			speed = 1,
		},
		iconFile = "speed",
	},
	{
		id = "buff_resist",
		isStack = true,
		name = strings.gift_stamina,
		tagList = { "buff" },
		resistTable = {
			witch = 0.15,
			fire_tag = 0.15,
			plague = 0.15,
		},
		iconFile = "shield_full",
	},
	{
		id = "sleep_halloween",
		tagList = { "debuff" },
		iconFile = "sleep",
		name = strings.sleep,
		effect = {
			isStun = true,
			isIgnoreDamage = true,
		},
		durationInRound = 5,
	},
	{
		id = "plague",
		isStack = true,
		name = strings.resist2,
		tagList = { "buff" },
		iconFile = "cauldron1",
		healing = 2500,
		effect = {
			selfDamageMult = -0.5,
		},
	},
	{
		id = "plague_cauldron",
		isStack = true,
		name = strings.plague,
		damage = 2500,
		tagList = { "debuff", "plague" },
		iconFile = "cauldron2",
	},
	{
		id = "buff_zombie",
		isStack = true,
		name = strings.effect_strength,
		tagList = { "buff" },
		effect = {
			damageMult = 0.7,
		},
		iconFile = "cauldron1",
	},
	{
		id = "buff_damage_frankenstein",
		isStack = true,
		name = strings.effect_strength,
		tagList = { "buff" },
		effect = {
			damageMult = 0.2,
			speed = 1,
		},
		iconFile = "sword",
	},
	{
		id = "buff_frankenstein",
		isStack = true,
		name = strings.effect_strength,
		tagList = { "buff" },
		effect = {
			damageMult = 0.2,
			speed = 2,
		},
		iconFile = "sword",
	},
	{
		id = "plague_reaper",
		isStack = true,
		name = strings.plague,
		tagList = { "debuff", "plague" },
		damage = 2500,
		durationInRound = 99,
		iconFile = "cauldron2",
	},
	{
		id = "fear_player",
		tagList = { "debuff" },
		iconFile = "pentagram",
		name = strings.fear,
		effect = {
			speed = -2,
		},
		durationInRound = 1,
	},
	{
		id = "electrogun_damage",
		isStack = true,
		name = strings.charge,
		tagList = { "buff" },
		iconFile = "energy",
		need = {
			{ "weapon", "tagList", "electrogun" },
		},
		effectWeapon = {
			damageMult = 0.2,
		},
		durationInRound = 2,
	},
	{
		id = "electrogun_resist",
		isStack = false,
		name = strings.resist2,
		tagList = { "buff" },
		iconFile = "energy",
		resistTable = {
			electrogun = 0.5,
		},
		durationInRound = 2,
	},
	{
		id = "quest_buff_speed",
		tagList = { "buff" },
		iconFile = "speed",
		name = strings.gift_speed,
		effect = {
			speed = 2,
		},
		durationInRound = 20,
	},
	{
		id = "quest_buff_range",
		tagList = { "buff" },
		iconFile = "range",
		need = {
			{ "weapon", "tagList", "range_tag" },
		},
		durationInRound = 20,
		effectWeapon = {
			range = 2,
		},
		name = strings.range,
	},
	{
		id = "quest_buff_resist",
		tagList = { "buff" },
		iconFile = "shield_full",
		name = strings.gift_stamina,
		effect = {
			selfDamageMult = -0.2,
		},
		durationInRound = 20,
	},
	{
		id = "quest_buff_fly",
		tagList = { "buff" },
		iconFile = "star",
		name = strings.diseases.magic_flight.name,
		effect = {
			isFly = true,
		},
		durationInRound = 20,
	},
	{
		id = "quest_buff_luck",
		tagList = { "buff" },
		iconFile = "luck",
		name = strings.luck,
		effect = {
			damageMult = 0.1,
		},
		durationInRound = 20,
	},
	{
		id = "quest_debuff_curse",
		tagList = { "debuff" },
		iconFile = "pentagram",
		name = strings.curse,
		effect = {
			selfDamageMult = 0.1,
		},
		durationInRound = 20,
	},
	{
		id = "quest_buff_regen",
		tagList = { "buff" },
		iconFile = "plus",
		name = strings.perk_regen,
		healing = 20,
		durationInRound = 10,
	},
	{
		id = "quest_debuff_damage",
		tagList = { "debuff" },
		iconFile = "pentagram",
		damage = 10,
		name = strings.diseases.poisoned_flask.name,
		durationInRound = 10,
	},
	{
		id = "block_attack",
		tagList = { "debuff" },
		iconFile = "down",
		effect = {
			isBlockAttack = true,
		},
		name = strings.disarmament,
	},
	{
		id = "invincible",
		tagList = { "buff" },
		iconFile = "shield_full",
		effect = {
			isIgnoreDamage = true,
		},
		name = strings.invulnerability,
	},
	{
		id = "ice_cream_effect",
		tagList = { "debuff" },
		iconFile = "freezed",
		name = strings.yummy_ice_cream,
		durationInRound = 2,
		healing = 200,
		effect = {
			isStun = true,
		},
	},
	{
		id = "possessed_civil",
		isStack = true,
		name = strings.ice_spite,
		text = strings.ice_psychosis_text,
		tagList = { "buff" },
		effect = {},
		iconFile = "possession",
	},
	{
		id = "vulnerability_endless",
		isStack = true,
		name = strings.vulnerability,
		tagList = { "debuff" },
		effect = {
			selfDamageMult = 0.15,
		},
		iconFile = "down",
	},
	{
		id = "resistance_endless",
		isStack = true,
		name = strings.gift_stamina,
		tagList = { "buff" },
		effect = {
			selfDamageMult = -0.15,
		},
		iconFile = "shield_full",
	},
	{
		id = "invincible_stack",
		tagList = { "buff" },
		iconFile = "shield_full",
		effect = {
			isIgnoreDamage = true,
			speed = -20,
		},
		name = strings.invulnerability,
	},
	{
		id = "weapon_resistance",
		tagList = { "buff" },
		iconFile = "shield_full",
		resistTable = {
			explosive_tag = 1,
			special = 1,
			physic = 1,
			witch = 1,
			acid = 1,
			range_tag = 1,
			snow = 1,
			electro_tag = 1,
			fire_tag = 1,
			plague = 1,
			magic = 1,
			melee_tag = 1,
			poison = 1,
			crossbow_tag = 1,
		},
		name = strings.invulnerability,
	},
	{
		id = "ny_boss6_buff2",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 3,
			damageMult = 60,
			apStart = 2,
			selfDamageMult = -0.4,
			apMax = 2,
			range = 3,
			speed = 1,
		},
		addArmor = 2200,
	},
	{
		id = "ny_boss6_buff3",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 3,
			damageMult = 20,
			apStart = 2,
			selfDamageMult = -0.2,
			apMax = 2,
			range = 2,
			speed = 1,
		},
		addArmor = 2000,
	},
	{
		id = "ny_boss6_buff4",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 3,
			damageMult = 10,
			apStart = 2,
			selfDamageMult = -0.2,
			apMax = 2,
			range = 1,
			speed = 1,
		},
		addArmor = 2000,
	},
	{
		id = "ny_boss6_buff5",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 3,
			damageMult = 5,
			apStart = 2,
			selfDamageMult = -0.15,
			apMax = 1,
			range = 1,
			speed = 1,
		},
		addArmor = 1800,
	},
	{
		id = "ny_boss6_buff6",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 3,
			damageMult = 3,
			apStart = 1,
			selfDamageMult = -0.15,
			apMax = 1,
			range = 1,
			speed = 1,
		},
		addArmor = 1700,
	},
	{
		id = "ny_boss6_buff7",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 2,
			selfDamageMult = -0.1,
			apStart = 1,
			apMax = 1,
			damageMult = 1.75,
		},
		addArmor = 1500,
	},
	{
		id = "ny_boss6_buff8",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			apRegen = 2,
			selfDamageMult = -0.1,
			apStart = 1,
			apMax = 1,
			damageMult = 0.7,
		},
		addArmor = 1000,
	},
	{
		id = "ny_boss6_buff9",
		tagList = { "buff" },
		iconFile = "new_year",
		name = strings.new_year,
		effect = {
			damageMult = 0.55,
		},
		addArmor = 500,
	},
	{
		id = "ny_boss6_protection",
		tagList = { "buff" },
		iconFile = "shield",
		effect = {
			isIgnoreDamage = true,
		},
		name = strings.defence,
	},
	{
		id = "brain_damage_low",
		tagList = { "debuff" },
		effect = {
			missChance = 0.7,
		},
		name = strings.ny_madness1.name,
		text = strings.ny_madness1.text,
		durationInRound = 1,
		iconFile = "brain",
	},
	{
		id = "brain_damage_mushrom",
		tagList = { "debuff" },
		effect = {
			missChance = 0.9,
		},
		name = strings.ny_madness1.name,
		text = strings.ny_madness1.text,
		durationInRound = 3,
		iconFile = "brain",
	},
	{
		id = "brain_damage",
		isAddChanceForWeak = true,
		isCharmEnemy = true,
		factionId = "snowman",
		tagList = { "debuff" },
		durationInRound = 2,
		name = strings.ny_madness2.name,
		text = strings.ny_madness2.text,
		iconFile = "crazy2",
	},
	{
		id = "brain_damage_boss4",
		tagList = { "debuff" },
		isAddChanceForWeak = true,
		isCharmEnemy = true,
		name = strings.ny_madness2.name,
		text = strings.ny_madness2.text,
		iconFile = "crazy2",
		durationInRound = 2,
	},
	{
		id = "brain_damage_fake",
		iconFile = "crazy2",
		durationInRound = 99,
		text = strings.ny_madness2.text,
		name = strings.ny_madness2.name,
	},
	{
		id = "quest_target_fake",
		name = strings.target,
		iconFile = "provoke",
		durationInRound = 99,
	},
	{
		id = "secret_debuff",
		isStack = true,
		name = strings.frozen_slowed,
		tagList = { "debuff" },
		iconFile = "down",
		effect = {
			dodgeChance = -0.25,
		},
		durationInRound = 2,
	},
	{
		id = "frozen_slowed",
		tagList = { "debuff" },
		iconFile = "slowed",
		name = strings.ice_trap,
		effect = {
			speed = -2,
		},
		durationInRound = 2,
	},
	{
		id = "frosthorn_damage",
		isStack = true,
		name = strings.vulnerability,
		tagList = { "debuff" },
		iconFile = "down",
		durationInRound = 2,
		resistTable = {
			snow = -0.2,
		},
		effect = {
			selfDamageMult = 0.2,
		},
	},
	{
		id = "launcher_rad",
		isStack = true,
		name = strings.radiation_damage,
		tagList = { "debuff", "radiation" },
		damage = 5,
		durationInRound = 5,
		iconFile = "rad1",
	},
	{
		id = "hack_range",
		isStack = true,
		name = strings.hack,
		tagList = { "debuff" },
		iconFile = "range_red",
		need = {
			{ "weapon", "tagList", "range_tag" },
		},
		effectWeapon = {
			range = -2,
		},
		durationInRound = 4,
	},
	{
		id = "cyber_resist",
		isStack = false,
		name = strings.hack,
		tagList = { "buff" },
		iconFile = "shield_full",
		effect = {
			selfDamageMult = -0.2,
		},
		durationInRound = 2,
	},
	{
		id = "hack_disarm",
		isStack = false,
		name = strings.hack,
		tagList = { "debuff" },
		iconFile = "arm",
		effect = {
			isBlockAttack = true,
		},
		durationInRound = 2,
	},
	{
		id = "possessed_civil",
		isStack = true,
		name = strings.ice_spite,
		text = strings.ice_psychosis_text,
		tagList = { "buff" },
		effect = {},
		iconFile = "possession",
	},
	{
		id = "vulnerability_endless",
		isStack = true,
		name = strings.vulnerability,
		tagList = { "debuff" },
		effect = {
			selfDamageMult = 0.25,
		},
		iconFile = "down",
	},
	{
		id = "resistance_endless",
		isStack = true,
		name = strings.gift_stamina,
		tagList = { "buff" },
		effect = {
			selfDamageMult = -0.15,
		},
		iconFile = "shield_full",
	},
	{
		id = "blindness_endless",
		tagList = { "debuff" },
		iconFile = "blindness",
		effect = {
			missChance = 0.2,
		},
		name = strings.blindness,
	},
	{
		id = "invincible_stack",
		tagList = { "buff" },
		iconFile = "shield_full",
		effect = {
			isIgnoreDamage = true,
			speed = -20,
		},
		name = strings.invulnerability,
	},
	{
		id = "armor_frostbite",
		isStack = true,
		name = strings.frostbite,
		tagList = { "debuff", "snow" },
		iconFile = "freezed",
		effect = {
			damageMult = -0.2,
		},
		durationInRound = 3,
	},
	{
		id = "quest_buff_dodge",
		tagList = { "buff" },
		iconFile = "cover",
		name = strings.perk_dodge,
		effect = {
			dodgeChance = 0.5,
		},
		durationInRound = 20,
	},
	{
		id = "quest_buff_counter",
		tagList = { "buff" },
		iconFile = "sword",
		name = strings.counterAttack,
		effectWeapon = {
			isCounterAttack = true,
		},
		durationInRound = 20,
	},
	{
		id = "snow_tacitc",
		tagList = { "buff" },
		iconFile = "speed",
		effect = {
			maxMove = 1,
		},
		name = strings.winterTactics,
	},
	{
		id = "vulnerability_endless_weak",
		isStack = true,
		name = strings.vulnerability,
		tagList = { "debuff" },
		effect = {
			selfDamageMult = 0.05,
		},
		iconFile = "down",
	},
	{
		id = "easter_fruit_effect",
		isStack = true,
		name = strings.encouraged,
		tagList = { "buff" },
		iconFile = "sword",
		effect = {
			selfDamageMult = -0.2,
			damageMult = 0.15,
		},
		durationInRound = 2,
	},
	{
		id = "effect_test",
		isStack = true,
		name = strings.gift_stamina,
		tagList = { "buff" },
		effect = {
			selfDamageArmorMult = 1,
		},
		iconFile = "shield_full",
	},
	{
		id = "trap_burning",
		isStack = true,
		effect = {
			speed = -10,
		},
		isOnlyText = true,
		tagList = { "debuff", "fire_tag" },
		durationInRound = 2,
		iconFile = "trap",
		damage = 5,
		text = strings.blockMove,
		name = strings.trap_burning,
	},
	{
		id = "armor_melt",
		tagList = { "debuff" },
		iconFile = "shield_broken",
		name = strings.effect_hw_pistol.name,
		effect = {
			selfDamageArmorMult = 0.2,
		},
		durationInRound = 2,
	},
	{
		id = "flesh_spawn",
		tagList = { "debuff" },
		textEffectList = {
			{
				text = strings.effect_hw_ar.text,
				isOnlyText = true,
			},
		},
		name = strings.effect_hw_ar.name,
		iconFile = "skull",
		damage = 10,
		addAfterDeath = {
			spawnUnits = { "ally_flesh" },
		},
		durationInRound = 2,
	},
	{
		id = "spider_chain",
		tagList = { "debuff" },
		name = strings.effect_hw_mg.name,
		text = strings.effect_hw_mg.text,
		addAfterDeath = {
			weapon = {
				id = "hw_spider1",
				isNearestAlly = true,
			},
		},
		iconFile = "spider",
	},
	{
		id = "spider_chain2",
		tagList = { "debuff" },
		name = strings.effect_hw_mg.name,
		text = strings.effect_hw_mg.text,
		addAfterDeath = {
			weapon = {
				id = "hw_spider2",
				isNearestAlly = true,
			},
		},
		iconFile = "spider",
	},
	{
		id = "rifle_ap",
		tagList = { "buff" },
		textEffectList = {
			{
				text = strings.effect_hw_rifle.text,
				valueId = { "effectWeapon", "ap" },
			},
			{
				text = strings.damage,
				value = -0.25,
				isPercent = true,
			},
		},
		name = strings.effect_hw_rifle.name,
		need = {
			{ "weapon", "tagList", "hw_rifle" },
		},
		durationInRound = 2,
		effectWeapon = {
			ap = -1,
			damageMult = -0.25,
		},
		iconFile = "energy",
	},
	
}