return {
-- ================== Custom
	-- Pets
	{
		id = "exp_agw_pet_ducky",
		name = strings.expPet,
		addTags = { "not_package" },
		image = "image/interface/icon/xp2.png",
	},
	{
		id = "exp_agw_pet_bear",
		name = strings.expPet,
		addTags = { "not_package" },
		image = "image/interface/icon/xp2.png",
	},

	-- Bases
	{
		id = "rep_agw_arkh",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_arkh.png",
	},
	{
		id = "rep_agw_pevek",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_pevek.png",
	},
	{
		id = "rep_agw_tiksi",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_tiksi.png",
	},
	{
		id = "rep_agw_vladi",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_vladi.png",
	},
	{
		id = "rep_agw_yakutsk",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_yakutsk.png",
	},
	{
		id = "rep_agw_skyt",
		name = strings.reputation,
		addTags = { "not_package", "service_tag" },
		image = "image/base_rep_icon/rep_agw_skyt.png",
	},

-- ================== Orig
	{
		id = "ad_tv",
		alwaysOnDrop = true,
		rank = 3,
		tagList = { "category_main", "decay_6m" },
		events = {
			craft1 = {
				name = strings.events.open,
				spendTime = 1,
				action = function()				
					main.profile.addCaps(main.profile, 15)
					main.animation.addItem(main.animation, "caps")
				end,
			},
		},
	},
	{
		imageFile = "premium_chest",
		id = "premium",
		rank = 5,
		tagList = { "not_package" },
		name = strings.buttons.premium,
	},
	{
		notDrop = true,
		id = "caps",
		tagList = { "shop", "not_package" },
		position = 0,
		rank = 5,
		isCaps = true,
	},
	{
		notDrop = true,
		id = "black_ruble",
		rank = 3,
		tagList = { "not_package" },
		isCurrency = true,
		currencyIconFile = "black_ruble",
	},
	{
		notDrop = true,
		id = "iron_nut",
		rank = 3,
		tagList = { "not_package" },
		isCurrency = true,
		currencyIconFile = "iron_nut",
	},
	{
		notDrop = true,
		id = "ration_card",
		rank = 3,
		tagList = { "not_package" },
		isCurrency = true,
		currencyIconFile = "ration_card",
	},
	{
		notDrop = true,
		id = "halloween_coin",
		rank = 3,
		description = strings.coins.description2,
		tagList = { "not_package" },
		isCurrency = true,
		name = strings.coins.name,
	},
	{
		notDrop = true,
		id = "halloween_soul",
		tagList = { "not_package" },
		isCurrency = true,
		rank = 3,
	},
	{
		notDrop = true,
		id = "ny_balls",
		rank = 3,
		description = strings.offer_ny.text,
		tagList = { "not_package" },
		isCurrency = true,
		name = strings.balls.name,
	},
	{
		notDrop = true,
		id = "ny_cookie",
		tagList = { "not_package" },
		isCurrency = true,
		rank = 3,
	},
	{
		notDrop = true,
		id = "emba_disk",
		tagList = { "not_package" },
		isCurrency = true,
		rank = 3,
	},
	{
		id = "random_item",
		image = "image/interface/icon/icon_question.png",
		addTags = { "not_package" },
		isRandomItem = true,
		name = strings.random_item,
	},
	{
		imageFile = "xp_boost_1",
		id = "xp_boost_1",
		tagList = { "category_tools", "not_package" },
		singleDepreciation = true,
		rank = 3,
	},
	{
		imageFile = "xp_boost_3",
		id = "xp_boost_3",
		tagList = { "category_tools", "not_package" },
		singleDepreciation = true,
		rank = 4,
	},
	{
		imageFile = "xp_boost_7",
		id = "xp_boost_7",
		tagList = { "category_tools", "not_package" },
		singleDepreciation = true,
		rank = 5,
	},
	{
		costAfterDeath = 5,
		weight = 50,
		id = "glue_tape",
		craftRecipeId = "glue_bone",
		isTagIcon = true,
		rank = 2,
		addTags = { "glue_tag", "not_package" },
		template = "component",
		name = strings.glue,
	},
	{
		addTags = { "not_package" },
		name = strings.events.exp,
		id = "exp",
		image = "image/interface/icon/xp1.png",
	},
	{
		addTags = { "not_package" },
		id = "lvl",
		isLevelOnIcon = true,
		name = strings.level,
	},
	{
		addTags = { "not_package" },
		name = strings.expPet,
		id = "exp_ally_raven",
		image = "image/interface/icon/xp2.png",
	},
	{
		addTags = { "not_package" },
		name = strings.expPet,
		id = "exp_ally_wolf",
		image = "image/interface/icon/xp2.png",
	},
	{
		addTags = { "not_package" },
		name = strings.expPet,
		id = "exp_ally_pumpkin",
		image = "image/interface/icon/xp2.png",
	},
	{
		addTags = { "not_package" },
		name = strings.expPet,
		id = "exp_ally_polar_fox",
		image = "image/interface/icon/xp2.png",
	},
	{
		addTags = { "not_package" },
		imageFile = "exp_halloween",
		id = "exp_halloween",
		name = strings.exp_halloween.name,
	},
	{
		addTags = { "not_package" },
		name = strings.expNewYear,
		id = "exp_new_year",
		image = "image/interface/icon/xp3.png",
	},
	{
		addTags = { "not_package" },
		name = strings.exp_emba.name,
		id = "exp_emba",
		image = "image/interface/icon/xp4.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_arzamas",
		image = "image/base_rep_icon/arzamas.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_briansk",
		image = "image/base_rep_icon/briansk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_chelyabinsk",
		image = "image/base_rep_icon/chelyabinsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_irkutsk",
		image = "image/base_rep_icon/irkutsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_izhevsk",
		image = "image/base_rep_icon/izhevsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_kiev",
		image = "image/base_rep_icon/kiev.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_krasnoyarsk",
		image = "image/base_rep_icon/krasnoyarsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_kurgan",
		image = "image/base_rep_icon/kurgan.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_leningrad",
		image = "image/base_rep_icon/leningrad.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_magnitogorsk",
		image = "image/base_rep_icon/magnitogorsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_novosibirsk",
		image = "image/base_rep_icon/novosibirsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_olonec",
		image = "image/base_rep_icon/olonec.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_omsk",
		image = "image/base_rep_icon/omsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_rostov",
		image = "image/base_rep_icon/rostov.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_ryazan",
		image = "image/base_rep_icon/ryazan.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_surgut",
		image = "image/base_rep_icon/surgut.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_sverdlovsk",
		image = "image/base_rep_icon/sverdlovsk.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_tula",
		image = "image/base_rep_icon/tula.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_tver",
		image = "image/base_rep_icon/tver.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_tymen",
		image = "image/base_rep_icon/tymen.png",
	},
	{
		addTags = { "not_package", "service_tag" },
		name = strings.reputation,
		id = "rep_voronej",
		image = "image/base_rep_icon/voronej.png",
	},
}