return {
  categoryList = {
    "popular",
    "consumables",
    "equipment",
    "weapon",
    "caps",
  },
  categoryTable = {
    caps = {
      { 110 },
      { 120, 121 },
      { 130, 131 },
      { 140, 141 },
      { 150, 151 },
      { 160, 161 },
    },
    weapon = {
      {
        "w_pps",
        "w_ppsh",
        "w_custom_ar",
        "w_aks74u",
        "w_ak74_single",
        "w_armorpiercer",
        "w_abakan",
      },
      {
        "w_pm",
        "w_nagant",
        "w_tt",
        "w_flamethrower",
        "w_aps",
        "w_rocket_launcher",
        "w_rpg7",
      },
      {
        "w_homemade_gun",
        "w_musket",
        "w_custom_rifle",
        "w_mosin",
        "w_mosin_sniper",
        "w_svt",
        "w_svd",
        "w_svu",
      },
      {
        "w_homemade_rifle",
        "w_izh",
        "w_toz",
        "w_saiga",
        "w_pepperbox",
      },
      {
        "w_custom_mg",
        "w_rpk74",
        "w_dp",
        "w_pk",
      },
      { "rpg7_ammo" },
      { "tt_ammo" },
      { "shotgun_ammo" },
      { "ak74_ammo" },
      { "mosin_ammo" },
    },
    popular = {
      { "energy_drink" },
      { "help_kit" },
      { "start_kit", "lootbox_component1" },
      { "gas_20k", "gas_50k", "gas_100k" },
      {
        "xp_1",
        "xp_2",
        "xp_3",
        "xp_4",
        "xp_5",
        "xp_6",
        "xp_7",
        "xp_8",
        "xp_9",
        "xp_10",
        "xp_11",
        "xp_12",
      },
      { "diesel_200k" },
      { "gunpowder_grenade", "f_1" },
      { "tn_primus" },
    },
    new_year = {
      { "ny1" },
      { "ny2" },
      { "ny3" },
      { "ny4" },
      { "ny5" },
      { "ny6" },
      { "ny7" },
      { "ny8" },
    },
    halloween = {
      { "hlw1" },
      { "hlw2" },
      { "hlw3" },
      { "hlw4" },
      { "hlw5" },
      { "hlw6" },
      { "hlw7" },
      { "hlw8" },
    },
    equipment = {
      {
        "ozk",
        "military_clothes2",
        "motorway_armor",
        "military_armor2",
        "leather_armor",
        "chitin_armor",
        "iron_armor",
        "steel_armor",
        "miner_armor",
      },
      {
        "gasmask1",
        "gasmask_mm",
        "gasmask2",
        "gasmask3",
        "gasmask4",
        "gasmask4",
        "gasmask_iron",
        "gasmask_oil",
        "gasmask_sova",
      },
      {
        "uaz",
        "uaz_s1",
        "gaz66",
        "gaz66_s1",
        "kamaz",
        "kamaz_s1",
        "kraz255",
        "kraz255_s1",
      },
      { "chopper", "chopper_s1" },
      { "bav485", "mi8" },
      { "belaz" },
    },
    helping = {},
    emba = {
      { "p_emba_disk1" },
      { "p_emba_disk2" },
      { "p_emba_herbicide" },
      { "p_emba_extractor" },
      { "p_emba_suit1" },
      { "p_emba_suit3" },
      { "p_emba_biomass" },
      { "p_emba_lootbox1" },
    },
    consumables = {
      { "flashlight_gold" },
      { "antirad" },
      { "medicine_kit" },
      { "gasmask_filter" },
      { "tools_kit" },
      { "batteryaaa" },
      { "titan_tools_kit" },
      { "water_filter2" },
    },
  },
  fuelNavigatorOffer = {
    gas = "gas_50k_popup",
    diesel = "diesel_100k_popup",
  },
  shopMailLimit = 2000,
  shopCategoryList = {
    {
      icon = "shop_icon_popular",
      textId = { "popular" },
      id = "popular",
    },
    {
      textId = { "sale" },
      id = "promo",
      icon = "shop_icon_offer",
      isNeedOffer = true,
    },
    {
      icon = "shop_icon_consumables",
      textId = { "consumables" },
      id = "consumables",
    },
    {
      icon = "shop_icon_equipment",
      textId = { "category", "category_equipment" },
      id = "equipment",
    },
    {
      icon = "shop_icon_weapon",
      textId = { "weapon" },
      id = "weapon",
    },
    {
      icon = "shop_icon_caps",
      textId = { "caps", "name" },
      id = "caps",
    },
    {
      textId = { "embaName" },
      needSeasonEvent = {
      },
      icon = "shop_icon_emba",
      id = "emba",
      currencyList = { "caps", "emba_disk" },
    },
    {
      textId = { "new_year" },      
      icon = "shop_icon_new_year",
      id = "new_year",
      currencyList = { "ny_balls", "ny_cookie" },
    },
    {
      icon = "shop_icon_mail",
      textId = { "mail" },
      id = "mail",
    },
  },
}