return {
-- ============== Custom
	{
		id = "agw_arkhangelsk_base",
		name = "Arkhangelsk Port City",
		imageFile = "arkh",
		imagePath = "image/base/arkh.jpg",
		bannerImageFile = "agw_arkhangelsk",

		nearLevel = 30,
		repList = { 0, 100, 250, 1000 },
		questLevelLimit = { 1, 50 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "arhangelsk",
		areaId = "agw_base_arkhangelsk",
		currencyId = "black_ruble",

		traderList = { "trader_agw_arkh" },
		workshopList = {
			{
				id = "workshop_agw_arkh",
			},
		},

		nearBaseList = { "base_olonec", "agw_tiksi_base" },
		repItemId = "rep_agw_arkh",

		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_arkh" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},
		npcEventList = { "emba_introman", "halloween_frightening", "halloween_minion_2023_1" },
	},
	{
		id = "agw_pevek_base",
		name = "Pevek Port City",
		imageFile = "pevek",
		imagePath = "image/base/pevek.jpg",
		bannerImageFile = "agw_pevek",

		nearLevel = 80,
		repList = { 0, 150, 500, 1500 },
		questLevelLimit = { 1, 100 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "city3965270",
		areaId = "agw_base_pevek",
		currencyId = "black_ruble",

		traderList = { "trader_agw_pevek" },
		workshopList = {
			{
				id = "workshop_agw_pevek",
			},
		},

		nearBaseList = { "agw_yakutsk_base", "agw_tiksi_base" },
		repItemId = "rep_agw_pevek",

		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_pevek" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},
		npcEventList = { "agw_hire_mercenary", "emba_introman", "halloween_frightening", "halloween_minion_2023_1" },
	},
	{
		id = "agw_tiksi_base",
		name = "Tiksi Port City",
		imageFile = "tiksi",
		imagePath = "image/base/tiksi.jpg",
		bannerImageFile = "agw_tiksi",

		nearLevel = 50,
		repList = { 0, 100, 400, 1000 },
		questLevelLimit = { 1, 60 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "city4127629",
		areaId = "agw_base_tiksi",
		currencyId = "black_ruble",

		traderList = { "trader_agw_tiksi" },
		workshopList = { "workshop_agw_tiksi" },

		nearBaseList = { "agw_pevek_base", "base_surgut" },
		repItemId = "rep_agw_tiksi",

		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_tiksi" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},
		npcEventList = { "agw_hire_mercenary", "emba_introman", "halloween_frightening", "halloween_minion_2023_1" },
	},
	{
		id = "agw_vladivostok_base",
		name = "Vladivostok",
		imageFile = "vladi",
		imagePath = "image/base/vladi.jpg",
		bannerImageFile = "agw_vladivostok",

		nearLevel = 95,
		repList = { 0, 250, 500, 1500 },
		questLevelLimit = { 1, 100 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "vladivostok",
		areaId = "agw_base_vladivostok",
		currencyId = "black_ruble",

		traderList = { "trader_agw_vladi" },
		workshopList = { "workshop_agw_vladi" },

		nearBaseList = { "agw_yakutsk_base", "base_irkutsk" },
		repItemId = "rep_agw_vladi",

		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_vladi" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},
		npcEventList = { "agw_hire_mercenary", "emba_introman", "halloween_frightening", "halloween_minion_2023_1" },
	},
	{
		id = "agw_yakutsk_base",
		name = "Yakutsk",
		imageFile = "yakutsk",
		imagePath = "image/base/yakutsk.jpg",
		bannerImageFile = "agw_yakutsk",

		nearLevel = 80,
		repList = { 0, 150, 400, 1000 },
		questLevelLimit = { 1, 100 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "yakutsk",
		areaId = "agw_base_yakutsk",
		currencyId = "black_ruble",

		traderList = { "trader_agw_yakutsk" },
		workshopList = { "workshop_agw_yakutsk" },

		nearBaseList = { "base_olonec" },
		repItemId = "rep_agw_yakutsk",

		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_yakutsk" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},
		npcEventList = { "agw_hire_mercenary", "emba_introman", "halloween_frightening", "halloween_minion_2023_1" },
	},
	{
		id = "agw_skyt_base",
		name = "Syktyvkar",
		imageFile = "skyt",
		imagePath = "image/base/skyt.jpg",
		bannerImageFile = "agw_skyt",

		nearLevel = 65,
		repList = { 0, 150, 600, 1000 },
		questLevelLimit = { 1, 70 },

		factionName = strings.faction.other,
		factionColor = "faction_other",
		cityId = "city7383649",
		areaId = "agw_base_skyt",
		currencyId = "black_ruble",

		traderList = { "trader_agw_skyt" },
		workshopList = { "workshop_agw_skyt" },

		nearBaseList = { "base_izhevsk", "agw_arkhangelsk_base" },
		repItemId = "rep_agw_skyt",

		npcEventList = {
			"agw_hire_mercenary",
			"agw_get_rodkin",
			"emba_introman", 
			"halloween_frightening", 
			"halloween_minion_2023_1",
		},
		nurseList = { "nurse_default" },
		buyerList = { "buyer_agw_skyt" },
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 80,
			set_up_devices = 60,
			reinforcement = 100,
			secret_documents = 60,
			comrade_in_trouble = 70,
			place_stash = 140,
			construction_team = 20,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 90,
			bandit_camp = 150,
			catch_thief = 20,
			camp_supply = 100,
			new_year_deliver_cloth = 30,
			intelligence = 30,
			scientist_rescue = 30,
			take_stash = 30,
			camp_defence = 100,
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = { "emba_event", isInvert = true },
				},
			},
		},		
	},

-- ============== Orig_default
	{
		id = "base_stepnoj",
		npcEventList = { "boris", "sasha" },
		factionName = strings.faction.other,
		name = strings.city.stepnoj_base,
		areaId = "stepnoj_base",
		notBarQuest = true,
		factionColor = "faction_other",
		notTeleportTarget = true,
		bannerImageFile = "stepnoj",
		imageId = "base_voronej",
	},
	{
		id = "base_olonec",
		npcEventList = {
			"boatman_camp_chat",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionName = strings.faction.other,
		name = strings.fishingVillage,
		bannerImageFile = "olonec",
		traderList = { "trader_olonec" },
		factionColor = "faction_other",
		currencyId = "black_ruble",
		nearBaseList = { "base_leningrad" },
		questEventRangeMult = {
			comrade_in_trouble = 16,
			construction_team = 8,
			ambush = 8,
			place_stash = 16,
			catch_thief = 8,
			bandit_camp = 8,
			reinforcement = 8,
			camp_supply = 16,
			cover_the_fighter = 8,
			take_stash = 16,
			destroy_lair = 8,
			scientist_rescue = 16,
			camp_defence = 8,
		},
		nearLevel = 1,
		repList = { 0, 50 },
		areaId = "base_olonec",
		repItemId = "rep_olonec",
		wheelOfFortuneList = { "wheel_default" },
		nurseList = { "nurse_default" },
		questCategoryList = {
			"order",
			"travel",
			"fight",
			"base_quest",
			"winter_base_quest",
		},
		buyerList = { "buyer_olonec" },
		questLevelLimit = { 1, 25 },
		imageFile = "olonec",
	},
	{
		id = "base_leningrad",
		npcEventList = {
			"guard_leningrad",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionName = strings.faction.other,
		name = strings.expeditionCamp,
		bannerImageFile = "leningrad",
		traderList = { "trader_leningrad" },
		factionColor = "faction_other",
		wheelOfFortuneList = { "wheel_default" },
		nearBaseList = { "base_olonec", "base_tver" },
		workshopList = { "workshop_leningrad" },
		questEventRangeMult = {
			comrade_in_trouble = 16,
			construction_team = 8,
			ambush = 8,
			place_stash = 16,
			catch_thief = 8,
			bandit_camp = 8,
			reinforcement = 8,
			camp_supply = 16,
			cover_the_fighter = 8,
			take_stash = 16,
			destroy_lair = 8,
			scientist_rescue = 16,
			camp_defence = 8,
		},
		nearLevel = 20,
		repList = { 0, 50, 100 },
		areaId = "base_leningrad",
		buyerList = { "buyer_leningrad" },
		currencyId = "black_ruble",
		nurseList = { "nurse_default" },
		questCategoryList = {
			"order",
			"travel",
			"fight",
			"base_quest",
			"winter_base_quest",
		},
		repItemId = "rep_leningrad",
		questLevelLimit = { 1, 30 },
		imageFile = "leningrad",
	},
	{
		id = "base_tver",
		npcEventList = {
			"svetlana",
			"emba_isaev_tver",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionName = strings.faction.other,
		name = strings.city.tver,
		bannerImageFile = "tver",
		traderList = { "trader_tver" },
		factionColor = "faction_other",
		currencyId = "black_ruble",
		imageId = "base_tver",
		nearBaseList = {
			"base_briansk",
			"base_tula",
			"base_ryazan",
		},
		addQuestCategory = {
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 3, 6 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_tver",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 3, 6 },
							"range",
						},
					},
					needQuestState = {
						{
							"emba_briefing",
							5,
							"<",
							isOr = true,
						},
						{
							"project_emba",
							1,
							">=",
						},
					},
				},
			},
		},
		tagList = { "faction_right" },
		nearLevel = 25,
		cityId = "tver",
		repList = { 0, 50, 150 },
		areaId = "tver_base",
		repItemId = "rep_tver",
		nurseList = { "nurse_default" },
		questEventRangeMult = {
			comrade_in_trouble = 36,
			place_stash = 36,
			take_stash = 36,
			construction_team = 18,
			ambush = 18,
			new_year_tree_quest = 18,
			scientist_rescue = 36,
			bandit_camp = 18,
			reinforcement = 18,
			camp_supply = 36,
			new_year_deliver_cloth = 18,
			catch_thief = 18,
			destroy_lair = 18,
			cover_the_fighter = 18,
			camp_defence = 18,
		},
		buyerList = { "buyer_tver" },
		wheelOfFortuneList = { "wheel_default" },
		questLevelLimit = { 1, 40 },
	},
	{
		id = "base_ryazan",
		questEventRangeMult = {
			comrade_in_trouble = 60,
			place_stash = 60,
			take_stash = 60,
			construction_team = 30,
			ambush = 30,
			new_year_tree_quest = 30,
			scientist_rescue = 60,
			bandit_camp = 30,
			reinforcement = 30,
			camp_supply = 60,
			new_year_deliver_cloth = 30,
			catch_thief = 30,
			destroy_lair = 30,
			cover_the_fighter = 30,
			camp_defence = 30,
		},
		factionName = strings.faction.other,
		name = strings.city.city9003571,
		bannerImageFile = "ryazan",
		npcRedirectTable = {
			base_guard = "guard_bandit",
		},
		traderList = { "trader_ryazan" },
		questLevelLimit = { 1, 45 },
		currencyId = "black_ruble",
		imageId = "base_ryazan",
		nearBaseList = {
			"base_briansk",
			"base_tver",
			"base_tula",
			"base_voronej",
			"base_arzamas",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_ryazan" },
		nearLevel = 30,
		cityId = "city9003571",
		areaId = "ryazan_base",
		repList = { 0, 50, 300 },
		repItemId = "rep_ryazan",
		nurseList = { "nurse_default" },
		npcEventList = {
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		buyerList = { "buyer_ryazan" },
		wheelOfFortuneList = { "wheel_default" },
		factionColor = "faction_other",
	},
	{
		id = "base_tula",
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 30,
			set_up_devices = 30,
			reinforcement = 30,
			secret_documents = 60,
			comrade_in_trouble = 60,
			place_stash = 60,
			construction_team = 30,
			cover_the_fighter = 30,
			new_year_tree_quest = 30,
			destroy_lair = 30,
			bandit_camp = 30,
			catch_thief = 30,
			camp_supply = 60,
			new_year_deliver_cloth = 30,
			intelligence = 60,
			scientist_rescue = 60,
			take_stash = 60,
			camp_defence = 30,
		},
		factionName = strings.faction.other,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.tula,
		bannerImageFile = "tula",
		traderList = { "trader_tula" },
		factionColor = "faction_other",
		currencyId = "black_ruble",
		imageId = "base_tula",
		nearBaseList = {
			"base_briansk",
			"base_tver",
			"base_ryazan",
			"base_voronej",
		},
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 8, 10 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 7, 10 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_tula",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 7, 10 },
							"range",
						},
					},
				},
			},
		},
		tagList = { "base_tag" },
		nearLevel = 35,
		cityId = "tula",
		repList = { 0, 50, 350 },
		areaId = "tula_base",
		buyerList = { "buyer_tula" },
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		repItemId = "rep_tula",
		npcEventList = {
			"nadezhda",
			"vanya",
			"ignat",
			"emba_isaev_tula",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		questLevelLimit = { 1, 50 },
	},
	{
		id = "base_briansk",
		questEventRangeMult = {
			science_polygon = 30,
			ambush = 30,
			set_up_devices = 30,
			reinforcement = 30,
			secret_documents = 60,
			comrade_in_trouble = 60,
			place_stash = 60,
			construction_team = 30,
			cover_the_fighter = 30,
			new_year_tree_quest = 30,
			destroy_lair = 30,
			bandit_camp = 30,
			catch_thief = 30,
			camp_supply = 60,
			new_year_deliver_cloth = 30,
			intelligence = 60,
			scientist_rescue = 60,
			take_stash = 60,
			camp_defence = 30,
		},
		factionName = strings.faction.other,
		name = strings.city.city5283670,
		bannerImageFile = "briansk",
		traderList = { "trader_briansk" },
		factionColor = "faction_other",
		currencyId = "black_ruble",
		imageId = "base_briansk",
		nearBaseList = {
			"base_gorenichi",
			"base_tver",
			"base_tula",
			"base_ryazan",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_briansk" },
		nearLevel = 40,
		cityId = "city5283670",
		areaId = "briansk_base",
		repList = { 0, 50, 200, 500 },
		repItemId = "rep_briansk",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_briansk" },
		npcEventList = {
			"varya",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		questLevelLimit = { 1, 55 },
	},
	{
		id = "base_gorenichi",
		questEventRangeMult = {
			science_polygon = 35,
			ambush = 35,
			set_up_devices = 35,
			reinforcement = 35,
			secret_documents = 70,
			comrade_in_trouble = 70,
			place_stash = 70,
			construction_team = 35,
			cover_the_fighter = 35,
			new_year_tree_quest = 35,
			destroy_lair = 35,
			bandit_camp = 35,
			catch_thief = 35,
			camp_supply = 70,
			new_year_deliver_cloth = 35,
			intelligence = 70,
			scientist_rescue = 70,
			take_stash = 70,
			camp_defence = 35,
		},
		factionName = strings.faction.other,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.kiev,
		bannerImageFile = "kiev",
		traderList = { "trader_kiev" },
		questLevelLimit = { 1, 60 },
		currencyId = "black_ruble",
		imageId = "base_rostov",
		nearBaseList = { "base_briansk" },
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 12, 14 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 11, 14 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_kiev",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 11, 14 },
							"range",
						},
					},
				},
			},
		},
		nearLevel = 45,
		cityId = "kiev",
		areaId = "gorenichi_base",
		repList = { 0, 50, 250, 550 },
		repItemId = "rep_kiev",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_kiev" },
		npcEventList = {
			"gavrilov",
			"zaycev",
			"emba_isaev_kiev",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_other",
	},
	{
		id = "base_voronej",
		questEventRangeMult = {
			science_polygon = 35,
			ambush = 35,
			set_up_devices = 35,
			reinforcement = 35,
			secret_documents = 70,
			comrade_in_trouble = 70,
			place_stash = 70,
			construction_team = 35,
			cover_the_fighter = 35,
			new_year_tree_quest = 35,
			destroy_lair = 35,
			bandit_camp = 35,
			catch_thief = 35,
			camp_supply = 70,
			new_year_deliver_cloth = 35,
			intelligence = 70,
			scientist_rescue = 70,
			take_stash = 70,
			camp_defence = 35,
		},
		factionName = strings.faction.other,
		name = strings.city.voronej,
		bannerImageFile = "voronej",
		npcRedirectTable = {
			base_guard = "guard_vdv",
		},
		traderList = { "trader_voronej" },
		questLevelLimit = { 1, 65 },
		currencyId = "black_ruble",
		imageId = "base_voronej",
		nearBaseList = {
			"base_tula",
			"base_ryazan",
			"base_rostov",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_voronej" },
		nearLevel = 50,
		cityId = "voronej",
		areaId = "voronej_base",
		repList = { 0, 50, 265, 700 },
		repItemId = "rep_voronej",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_voronej" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_other",
	},
	{
		id = "base_rostov",
		questEventRangeMult = {
			science_polygon = 45,
			ambush = 45,
			set_up_devices = 45,
			reinforcement = 45,
			secret_documents = 85,
			comrade_in_trouble = 85,
			place_stash = 85,
			construction_team = 45,
			cover_the_fighter = 45,
			new_year_tree_quest = 45,
			destroy_lair = 45,
			bandit_camp = 45,
			catch_thief = 45,
			camp_supply = 85,
			new_year_deliver_cloth = 45,
			intelligence = 85,
			scientist_rescue = 85,
			take_stash = 85,
			camp_defence = 45,
		},
		factionName = strings.faction.other,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city['rostov-na-donu'],
		bannerImageFile = "rostov",
		traderList = { "trader_rostov" },
		questLevelLimit = { 1, 70 },
		currencyId = "black_ruble",
		imageId = "base_rostov",
		nearBaseList = { "base_voronej" },
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 16, 18 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 15, 18 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_rostov",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 15, 18 },
							"range",
						},
					},
				},
			},
		},
		nearLevel = 55,
		cityId = "rostov-na-donu",
		areaId = "rostov_base",
		repList = { 0, 50, 285, 750 },
		repItemId = "rep_rostov",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_rostov" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_isaev_rostov",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_other",
	},
	{
		id = "base_arzamas",
		questEventRangeMult = {
			science_polygon = 50,
			ambush = 50,
			set_up_devices = 50,
			reinforcement = 50,
			secret_documents = 100,
			comrade_in_trouble = 100,
			place_stash = 100,
			construction_team = 50,
			cover_the_fighter = 50,
			new_year_tree_quest = 50,
			destroy_lair = 50,
			bandit_camp = 50,
			catch_thief = 50,
			camp_supply = 100,
			new_year_deliver_cloth = 50,
			intelligence = 100,
			scientist_rescue = 100,
			take_stash = 100,
			camp_defence = 50,
		},
		factionName = strings.faction.other,
		name = strings.city.city2468338,
		bannerImageFile = "arzamas",
		npcRedirectTable = {
			base_guard = "guard_arzamas",
		},
		traderList = { "trader_arzamas" },
		questLevelLimit = { 1, 75 },
		currencyId = "black_ruble",
		imageId = "base_arzamas",
		nearBaseList = { "base_ryazan", "base_izhevsk" },
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_arzamas" },
		nearLevel = 60,
		cityId = "city2468338",
		areaId = "arzamas_base",
		repList = {
			0,
			50,
			190,
			475,
			900,
		},
		repItemId = "rep_arzamas",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_arzamas" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_other",
	},
	{
		id = "base_izhevsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.other,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.izhevsk,
		bannerImageFile = "izhevsk",
		traderList = { "trader_izhevsk" },
		factionColor = "faction_other",
		currencyId = "black_ruble",
		imageId = "base_izhevsk",
		tagList = { "gigahive_quest" },
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 20, 22 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 19, 22 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_izhevsk",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 19, 22 },
							"range",
						},
					},
				},
			},
		},
		npcEventList = {
			"agw_hire_mercenary",
			"gigahive_bar",
			"emba_isaev_izhevsk",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		nearLevel = 65,
		cityId = "izhevsk",
		areaId = "izhevsk_base",
		repList = {
			0,
			50,
			350,
			950,
			1850,
		},
		buyerList = { "buyer_izhevsk" },
		nurseList = { "nurse_default" },
		nearBaseList = { "base_arzamas", "base_sverdlovsk" },
		repItemId = "rep_izhevsk",
		wheelOfFortuneList = { "wheel_default" },
		questLevelLimit = { 1, 80 },
	},
	{
		id = "base_magnitogorsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.red,
		name = strings.city.magnitogorsk,
		bannerImageFile = "magnitogorsk",
		npcRedirectTable = {
			base_guard = "guard_brigade",
		},
		traderList = { "trader_magnitogorsk" },
		factionColor = "faction_red",
		currencyId = "iron_nut",
		imageId = "base_magnitogorsk",
		tagList = { "faction_blue" },
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_magnitogorsk" },
		repList = {
			0,
			50,
			180,
			440,
			830,
		},
		nearLevel = 70,
		cityId = "magnitogorsk",
		areaId = "base2",
		nearBaseList = {
			"base_sverdlovsk",
			"base_chelyabinsk",
			"base_tymen",
			"base_kurgan",
		},
		buyerList = { "buyer_magnitogorsk" },
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		repItemId = "rep_magnitogorsk",
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		questLevelLimit = { 1, 90 },
	},
	{
		id = "base_chelyabinsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.red,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.chelyabinsk,
		trainList = { "train_siberia" },
		bannerImageFile = "chelyabinsk",
		npcRedirectTable = {
			base_guard = "guard_brigade",
		},
		traderList = { "trader_chelyabinsk" },
		factionColor = "faction_red",
		currencyId = "iron_nut",
		imageId = "base_chelyabinsk",
		nearBaseList = {
			"base_sverdlovsk",
			"base_magnitogorsk",
			"base_tymen",
			"base_kurgan",
		},
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 24, 26 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 23, 26 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_chelyabinsk",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 23, 26 },
							"range",
						},
					},
				},
			},
		},
		tagList = { "faction_blue" },
		nearLevel = 70,
		cityId = "chelyabinsk",
		repList = { 0, 50, 520, 1465 },
		areaId = "chelyabinsk_base",
		buyerList = { "buyer_chelyabinsk" },
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		repItemId = "rep_chelyabinsk",
		npcEventList = {
			"agw_hire_mercenary",
			"spiridon",
			"emba_isaev_chelyabinsk",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		questLevelLimit = { 1, 90 },
	},
	{
		id = "base_sverdlovsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.red,
		name = strings.city.ekaterinburg,
		bannerImageFile = "sverdlovsk",
		npcRedirectTable = {
			base_guard = "guard_brigade",
		},
		traderList = { "trader_sverdlovsk" },
		factionColor = "faction_red",
		currencyId = "iron_nut",
		imageId = "base_sverdlovsk",
		tagList = { "faction_blue" },
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_sverdlovsk" },
		repList = { 0, 50, 630, 1790 },
		nearLevel = 70,
		cityId = "ekaterinburg",
		areaId = "base4",
		nearBaseList = {
			"base_chelyabinsk",
			"base_magnitogorsk",
			"base_tymen",
			"base_kurgan",
		},
		buyerList = { "buyer_sverdlovsk" },
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		repItemId = "rep_sverdlovsk",
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		questLevelLimit = { 1, 90 },
	},
	{
		id = "base_kurgan",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.yellow,
		name = strings.city.city9841915,
		trainList = { "train_siberia" },
		bannerImageFile = "kurgan",
		npcRedirectTable = {
			base_guard = "guard_bandit",
		},
		traderList = { "trader_kurgan" },
		questLevelLimit = { 1, 100 },
		currencyId = "iron_nut",
		imageId = "base_kurgan",
		nearBaseList = {
			"base_sverdlovsk",
			"base_chelyabinsk",
			"base_magnitogorsk",
			"base_tymen",
			"base_surgut",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_kurgan" },
		nearLevel = 80,
		cityId = "city9841915",
		areaId = "kurgan_base",
		repList = { 0, 50, 710, 2030 },
		repItemId = "rep_kurgan",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_kurgan" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_yellow",
	},
	{
		id = "base_tymen",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.yellow,
		name = strings.city.tymen,
		trainList = { "train_siberia" },
		bannerImageFile = "tymen",
		npcRedirectTable = {
			base_guard = "guard_bandit",
		},
		traderList = { "trader_tymen" },
		questLevelLimit = { 1, 100 },
		currencyId = "iron_nut",
		imageId = "base_tymen",
		nearBaseList = {
			"base_sverdlovsk",
			"base_chelyabinsk",
			"base_magnitogorsk",
			"base_kurgan",
			"base_surgut",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_tymen" },
		nearLevel = 80,
		cityId = "tymen",
		areaId = "tymen_base",
		repList = { 0, 50, 395, 1080 },
		repItemId = "rep_tymen",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_tymen" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_yellow",
	},
	{
		id = "base_surgut",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.yellow,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.city5942259,
		bannerImageFile = "surgut",
		npcRedirectTable = {
			base_guard = "guard_bandit",
		},
		traderList = { "trader_surgut" },
		questLevelLimit = { 1, 100 },
		currencyId = "iron_nut",
		imageId = "base_surgut",
		nearBaseList = {
			"base_sverdlovsk",
			"base_chelyabinsk",
			"base_magnitogorsk",
			"base_tymen",
			"base_kurgan",
		},
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 28, 30 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 27, 30 },
							"range",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_surgut",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 27, 30 },
							"range",
						},
					},
				},
			},
		},
		nearLevel = 80,
		cityId = "city5942259",
		areaId = "surgut_base",
		repList = { 0, 50, 395 },
		repItemId = "rep_surgut",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_surgut" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_isaev_surgut",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_yellow",
	},
	{
		id = "base_omsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.other,
		name = strings.city.omsk,
		trainList = { "train_siberia" },
		bannerImageFile = "omsk",
		traderList = { "trader_omsk" },
		questLevelLimit = { 1, 100 },
		currencyId = "ration_card",
		imageId = "base_omsk",
		nearBaseList = { "base_novosibirsk", "base_kurgan" },
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_omsk" },
		nearLevel = 90,
		cityId = "omsk",
		areaId = "omsk_base",
		repList = { 0, 50, 365, 1000 },
		repItemId = "rep_omsk",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_omsk" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_other",
	},
	{
		id = "base_novosibirsk",
		questEventRangeMult = {
			science_polygon = 60,
			ambush = 60,
			set_up_devices = 60,
			reinforcement = 60,
			secret_documents = 120,
			comrade_in_trouble = 120,
			place_stash = 120,
			construction_team = 60,
			cover_the_fighter = 60,
			new_year_tree_quest = 60,
			destroy_lair = 60,
			bandit_camp = 60,
			catch_thief = 60,
			camp_supply = 120,
			new_year_deliver_cloth = 60,
			intelligence = 120,
			scientist_rescue = 120,
			take_stash = 120,
			camp_defence = 60,
		},
		factionName = strings.faction.blue,
		name = strings.city.novosibirsk,
		trainList = { "train_siberia" },
		bannerImageFile = "novosibirsk",
		npcRedirectTable = {
			base_guard = "guard_science",
		},
		traderList = { "trader_novosibirsk" },
		questLevelLimit = { 1, 100 },
		currencyId = "ration_card",
		imageId = "base_novosibirsk",
		nearBaseList = {
			"base_omsk",
			"base_krasnoyarsk",
			"base_irkutsk",
		},
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_novosibirsk" },
		nearLevel = 90,
		cityId = "novosibirsk",
		areaId = "novosibirsk_base",
		repList = {
			0,
			50,
			210,
			525,
			1000,
		},
		repItemId = "rep_novosibirsk",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_novosibirsk" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_blue",
	},
	{
		id = "base_krasnoyarsk",
		questEventRangeMult = {
			science_polygon = 90,
			ambush = 90,
			set_up_devices = 90,
			reinforcement = 90,
			secret_documents = 180,
			comrade_in_trouble = 180,
			place_stash = 180,
			construction_team = 90,
			cover_the_fighter = 90,
			new_year_tree_quest = 90,
			destroy_lair = 90,
			bandit_camp = 90,
			catch_thief = 90,
			camp_supply = 180,
			new_year_deliver_cloth = 90,
			intelligence = 180,
			scientist_rescue = 180,
			take_stash = 180,
			camp_defence = 90,
		},
		factionName = strings.faction.blue,
		npcRepTable = {
			emba_labortory = { 0, 2 },
		},
		name = strings.city.krasnoyarsk,
		trainList = { "train_siberia" },
		bannerImageFile = "krasnoyarsk",
		npcRedirectTable = {
			base_guard = "guard_science",
		},
		traderList = { "trader_krasnoyarsk" },
		questLevelLimit = { 1, 100 },
		currencyId = "ration_card",
		imageId = "base_krasnoyarsk",
		nearBaseList = { "base_novosibirsk", "base_irkutsk" },
		addQuestCategory = {
			{
				id = "emba_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							{ 32, 34 },
							"range",
						},
					},
				},
			},
			{
				id = "emba_dcomp_quest",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							31,
							">=",
						},
					},
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = {
			{
				id = "workshop_krasnoyarsk",
			},
			{
				id = "emba_laboratory",
				eventForAccess = {
					needState = {
						{
							{ "npcKeyTable", "emba_isaev" },
							31,
							">=",
						},
					},
				},
			},
		},
		nearLevel = 90,
		cityId = "krasnoyarsk",
		areaId = "krasnoyarsk_base",
		repList = { 0, 50, 365, 1000 },
		repItemId = "rep_krasnoyarsk",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_krasnoyarsk" },
		npcEventList = {
			"agw_hire_mercenary",
			"emba_isaev_krasnoyarsk",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_blue",
	},
	{
		id = "base_irkutsk",
		questEventRangeMult = {
			science_polygon = 90,
			ambush = 90,
			set_up_devices = 90,
			reinforcement = 90,
			secret_documents = 180,
			comrade_in_trouble = 180,
			place_stash = 180,
			construction_team = 90,
			cover_the_fighter = 90,
			new_year_tree_quest = 90,
			destroy_lair = 90,
			bandit_camp = 90,
			catch_thief = 90,
			camp_supply = 180,
			new_year_deliver_cloth = 90,
			intelligence = 180,
			scientist_rescue = 180,
			take_stash = 180,
			camp_defence = 90,
		},
		factionName = strings.faction.blue,
		name = strings.city.irkutsk,
		trainList = { "train_siberia" },
		bannerImageFile = "irkutsk",
		npcRedirectTable = {
			base_guard = "guard_science",
		},
		traderList = { "trader_irkutsk" },
		questLevelLimit = { 1, 100 },
		currencyId = "ration_card",
		imageId = "base_irkutsk",
		nearBaseList = { "base_novosibirsk", "base_krasnoyarsk" },
		addQuestCategory = {
			{
				id = "emba_bar_quest",
				eventForAccess = {
					needSeasonDate = {
						"emba_event",
						isInvert = true,
					},
				},
			},
		},
		workshopList = { "workshop_irkutsk" },
		nearLevel = 90,
		cityId = "irkutsk",
		areaId = "irkutsk_base",
		repList = { 0, 50, 365, 1000 },
		repItemId = "rep_irkutsk",
		nurseList = { "nurse_default" },
		wheelOfFortuneList = { "wheel_default" },
		buyerList = { "buyer_irkutsk" },
		npcEventList = {
			"agw_hire_mercenary",
			"belaz",
			"emba_introman",
			"halloween_frightening",
			"halloween_minion_2023_1",
		},
		factionColor = "faction_blue",
	},

-- ============== Orig Events
	{
		id = "bar_halloween",
		name = strings.honestDevil,
		notRefreshBase = true,
		notQuestLimit = true,
		questLevelLimit = { 1, 100 },
		imageId = "base_halloween",
		barNpcId = "shadow_barman",
		currencyId = "halloween_soul",
		bannerImage = "image/banner/halloween.png",
	},
	{
		id = "bar_new_year",
		name = strings.snowMaiden,
		notRefreshBase = true,
		notQuestLimit = true,
		timeSlotUpdate = 7200,
		isNewYear = true,
		questLevelLimit = { 1, 100 },
		bannerImage = "image/banner/halloween.png",
		barNpcId = "snowmaiden",
		imageId = "base_halloween",
		questCategoryList = { "new_year_boss", "new_year" },
	},
	{
		id = "bar_emba",
		notRefreshBase = true,
		name = strings.snowMaiden,
		notQuestLimit = true,
		timeSlotUpdate = 7200,
		imageId = "base_halloween",
		questLevelLimit = { 1, 100 },
		questCategoryList = { "new_year_boss", "new_year" },
		barNpcId = "snowmaiden",
		bannerImage = "image/banner/halloween.png",
	},

}