return {
	{
		mapId = { "beehive1_8lvl", "beehive2_8lvl", "beehive3_8lvl" },
		exp = 250,
		id = "bee_mother8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "wax", 1 },
		},
		list = { "bee_mother8" },
		isInstantBattle = true,
	},
	{
		mapId = { "beehive1_9lvl", "beehive2_9lvl", "beehive3_9lvl" },
		exp = 300,
		id = "bee_mother9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "wax", 1 },
		},
		list = { "bee_mother9" },
		isInstantBattle = true,
	},
	{
		mapId = { "beehive1_10lvl", "beehive2_10lvl", "beehive3_10lvl" },
		exp = 400,
		id = "bee_mother10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_6", 1 },
			{ "wax", 1 },
		},
		list = { "bee_mother10" },
		isInstantBattle = true,
	},
	{
		mapId = "beequeen_stage1",
		exp = 100,
		id = "beequeen9_stage1",
		isInstantBattle = true,
		list = {
			"bee_soldier_mother9",
			"bee_soldier_mother9",
			"bee_soldier_mother9",
			"bee_toxic_mother9",
			"bee_toxic_mother9",
		},
		isFixedPosition = true,
	},
	{
		mapId = "beequeen_stage2",
		exp = 180,
		id = "beequeen9_stage2",
		isInstantBattle = true,
		list = { "bee_mother9" },
		isFixedPosition = true,
	},
	{
		mapId = "beequeen_stage3",
		exp = 300,
		id = "beequeen9_stage3",
		isFixedPosition = true,
		loot = {
			{ "wax", 5 },
		},
		list = {
			"bee_queen_sleep9",
			"bee_tower_sleep9",
			"bee_tower_sleep9",
			"bee_tower_sleep9",
			"bee_soldier_mother9",
			"bee_soldier_mother9",
			"bee_toxic_mother9",
			"bee_toxic_mother9",
		},
		isInstantBattle = true,
	},
	{
		mapId = "beequeen_stage1",
		exp = 120,
		id = "beequeen10_stage1",
		isInstantBattle = true,
		list = {
			"bee_soldier_mother10",
			"bee_soldier_mother10",
			"bee_soldier_mother10",
			"bee_toxic_mother10",
			"bee_toxic_mother10",
		},
		isFixedPosition = true,
	},
	{
		mapId = "beequeen_stage2",
		exp = 250,
		id = "beequeen10_stage2",
		isInstantBattle = true,
		list = { "bee_mother10" },
		isFixedPosition = true,
	},
	{
		mapId = "beequeen_stage3",
		exp = 400,
		id = "beequeen10_stage3",
		isFixedPosition = true,
		loot = {
			{ "wax", 20 },
		},
		list = {
			"bee_queen_sleep10",
			"bee_tower_sleep10",
			"bee_tower_sleep10",
			"bee_tower_sleep10",
			"bee_soldier_mother10",
			"bee_soldier_mother10",
			"bee_toxic_mother10",
			"bee_toxic_mother10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "ant_boss_1",
		id = "ant_queen_1",
		isInstantBattle = true,
		list = {
			"ant_grappler2",
			"ant_officer",
			"ant_officer",
			"ant_grappler",
			"ant_officer",
			"ant_grappler",
		},
		isFixedPosition = true,
	},
	{
		mapId = "ant_boss_2",
		id = "ant_queen_2",
		isInstantBattle = true,
		list = {
			"ant_not_queen",
			"ant_officer",
			"ant_grappler",
			"ant_officer",
			"ant_grappler2",
			"ant_officer",
			"ant_officer",
		},
		isFixedPosition = true,
	},
	{
		mapId = "ant_boss_3",
		id = "ant_queen_3",
		isInstantBattle = true,
		list = { "ant_queen_stage_1", "ant_officer", "ant_officer" },
		isFixedPosition = true,
	},
	{
		mapId = "infected_shop_miniboss_3",
		exp = 5,
		id = "base_insect_1",
		isInstantBattle = true,
		list = { "infected_shop_mutant_1", "cockroach_lootless" },
		isFixedPosition = true,
	},
	{
		mapId = "infected_shop_miniboss_3",
		exp = 10,
		id = "base_insect_2",
		isInstantBattle = true,
		list = {
			"infected_shop_mutant_2",
			"infected_shop_mutant_2",
			"infected_shop_mutant_2",
			"infected_shop_mutant_2",
		},
		isFixedPosition = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 20,
		id = "base_insect_3",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"infected_shop_mutant_3",
			"infected_shop_mutant_3",
			"infected_shop_mutant_3_2",
			"infected_shop_mutant_3_2",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 40,
		id = "base_insect_4",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_2", 1 },
		},
		list = { "infected_shop_mutant_4_2", "infected_shop_mutant_4", "centipede_lootless" },
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 60,
		id = "base_insect_5",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"infected_shop_mutant_5",
			"centipede_lootless",
			"centipede_lootless",
			"centipede_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 100,
		id = "base_insect_6",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_2", 1 },
			{ "pan_rust", 1 },
		},
		list = {
			"infected_shop_mutant_6",
			"infected_shop_mutant_6_2",
			"infected_shop_mutant_6_2",
			"centipede_lootless",
			"centipede_lootless",
			"infected_shop_mutant_5",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 160,
		id = "base_insect_7",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_3", 1 },
			{ "watch", 1 },
		},
		list = {
			"infected_shop_mutant_7",
			"spider_mutant_lootless",
			"infected_shop_mutant_7_2",
			"infected_shop_mutant_7_2",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 250,
		id = "base_insect_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"infected_shop_mutant_8",
			"spider_mutant_lootless",
			"infected_shop_mutant_8_2",
			"infected_shop_mutant_8_3",
			"infected_shop_mutant_8_3",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 300,
		id = "base_insect_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_3", 1 },
			{ "copper_coin", 50 },
		},
		list = {
			"infected_shop_mutant_9",
			"scorpion_lootless",
			"scorpion_lootless",
			"scorpion_lootless",
			"spider_mutant_lootless",
			"infected_shop_mutant_9_2",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "infected_shop_miniboss_3", "infected_shop_5", "infected_shop_6" },
		exp = 400,
		id = "base_insect_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_1", 1 },
			{ "dice_rare", 1 },
		},
		list = {
			"infected_shop_mutant_10",
			"infected_shop_mutant_10_2",
			"scorpion_lootless",
			"scorpion_lootless",
			"scorpion_lootless",
			"scorpion_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss", "madman_house_7", "madman_house" },
		exp = 20,
		id = "base_mad_man_3",
		isInstantBattle = true,
		list = {
			"madman_base_3",
			"mad_man_big_lootless",
			"mad_man_crossbow_3",
			"mad_man_crossbow_3",
			"mad_man_crossbow_3",
		},
		isFixedPosition = true,
	},
	{
		mapId = { "madman_house_miniboss", "madman_house_7", "madman_house" },
		exp = 40,
		id = "base_mad_man_4",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"madman_base_4",
			"mad_man_big_lootless",
			"mad_man_crossbow_4",
			"mad_man_club_4",
			"mad_man_crossbow_4",
			"mad_man_club_4",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss", "madman_house_7", "madman_house" },
		exp = 60,
		id = "base_mad_man_5",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"madman_base_5",
			"mad_man_big_5",
			"mad_man_crossbow_5",
			"mad_man_club_5",
			"mad_man_club_5",
			"mad_man_crossbow_5",
			"mad_man_crossbow_5",
			"mad_man_club_5",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss", "madman_house_7", "madman_house" },
		exp = 100,
		id = "base_mad_man_6",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"madman_base_6",
			"mad_man_big_6",
			"mad_man_crossbow_6",
			"mad_man_club_6",
			"mad_man_club_6",
			"mad_man_crossbow_6",
			"mad_man_crossbow_6",
			"mad_man_club_6",
			"mad_man_crossbow_6",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss_1", "madman_house_miniboss_2", "madman_house_miniboss_3" },
		exp = 160,
		id = "base_mad_man_7",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"madman_base_7",
			"mad_man_big_7",
			"mad_man_crossbow_7",
			"mad_man_club_7",
			"mad_man_club_7",
			"mad_man_crossbow_7",
			"mad_man_crossbow_7",
			"mad_man_club_7",
			"mad_man_big_7",
			"mad_man_crossbow_7",
			"mad_man_club_7",
			"mad_man_club_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss_1", "madman_house_miniboss_2", "madman_house_miniboss_3" },
		exp = 250,
		id = "base_mad_man_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_1", 1 },
			{ "bottled_water", 10 },
		},
		list = {
			"madman_base_8",
			"mad_man_big_8",
			"mad_man_crossbow_8",
			"mad_man_crossbow_8",
			"mad_man_club_8",
			"mad_man_crossbow_8",
			"mad_man_club_8",
			"mad_man_big_8",
			"mad_man_big_8",
			"mad_man_crossbow_8",
			"mad_man_club_8",
			"mad_man_club_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss_1", "madman_house_miniboss_2", "madman_house_miniboss_3" },
		exp = 300,
		id = "base_mad_man_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"madman_base_9",
			"mad_man_big_9",
			"mad_man_crossbow_9",
			"mad_man_club_9",
			"mad_man_club_9",
			"mad_man_crossbow_9",
			"mad_man_crossbow_9",
			"mad_man_big_9",
			"mad_man_crossbow_9",
			"mad_man_big_9",
			"mad_man_crossbow_9",
			"mad_man_club_9",
			"mad_man_club_9",
			"mad_man_club_9",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "madman_house_miniboss_1", "madman_house_miniboss_2", "madman_house_miniboss_3" },
		exp = 400,
		id = "base_mad_man_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"madman_base_10",
			"mad_man_big_10",
			"mad_man_crossbow_10",
			"mad_man_club_10",
			"mad_man_club_10",
			"mad_man_crossbow_10",
			"mad_man_club_10",
			"mad_man_crossbow_10",
			"mad_man_big_10",
			"mad_man_crossbow_10",
			"mad_man_club_10",
			"mad_man_crossbow_10",
			"mad_man_club_10",
			"mad_man_club_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 40,
		id = "base_marauder_4",
		isInstantBattle = true,
		list = { "marauder_garage_4", "marauder_shotgun_4", "marauder_nagant_4" },
		isFixedPosition = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 60,
		id = "base_marauder_5",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"marauder_garage_5",
			"marauder_shotgun_5",
			"marauder_nagant_5",
			"marauder_garage_4",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 100,
		id = "base_marauder_6",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
			{ "copper_coin", 50 },
		},
		list = {
			"marauder_garage_6",
			"marauder_shotgun_6",
			"marauder_rifle_6",
			"marauder_nagant_6",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 160,
		id = "base_marauder_7",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_4", 1 },
			{ "bottled_water", 10 },
		},
		list = {
			"marauder_garage_7",
			"marauder_shotgun_7",
			"marauder_rifle_7",
			"marauder_nagant_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 250,
		id = "base_marauder_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"marauder_garage_8",
			"marauder_shotgun_8",
			"marauder_rifle_8",
			"marauder_garage_7",
			"marauder_nagant_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 300,
		id = "base_marauder_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"marauder_garage_9",
			"marauder_shotgun_9",
			"marauder_rifle_9",
			"marauder_garage_9",
			"marauder_nagant_9",
			"marauder_shotgun_9",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "marauder_garage_miniboss", "marauder_garage_5", "marauder_garage_7" },
		exp = 400,
		id = "base_marauder_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"marauder_garage_10",
			"marauder_shotgun_10",
			"marauder_rifle_10",
			"marauder_garage_10",
			"marauder_nagant_10",
			"marauder_rifle_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "beehive_miniboss", "beehive_miniboss_2" },
		exp = 100,
		id = "base_bee_6",
		isInstantBattle = true,
		list = { "bee_lair_6", "bee_soldier_6" },
		isFixedPosition = true,
	},
	{
		mapId = { "beehive_miniboss", "beehive_miniboss_2" },
		exp = 160,
		id = "base_bee_7",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
		},
		list = { "bee_lair_7", "bee_soldier_lootless", "bee_worker_lootless" },
		isInstantBattle = true,
	},
	{
		mapId = { "beehive_miniboss", "beehive_miniboss_2" },
		exp = 250,
		id = "base_bee_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = { "bee_lair_8", "bee_soldier_lootless", "bee_guard_lootless" },
		isInstantBattle = true,
	},
	{
		mapId = { "beehive_miniboss", "beehive_miniboss_2" },
		exp = 300,
		id = "base_bee_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_3", 1 },
		},
		list = { "bee_lair_9", "wasp_9", "bee_guard_lootless" },
		isInstantBattle = true,
	},
	{
		mapId = { "beehive_miniboss", "beehive_miniboss_2" },
		exp = 400,
		id = "base_bee_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"bee_lair_10",
			"hornet_lootless",
			"bee_guard_lootless_10",
			"bee_guard_lootless_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "lair_ant_miniboss", "lair_ant_miniboss_2" },
		exp = 250,
		id = "base_ant_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"ant_lair_boss_8",
			"ant_worker_lootless",
			"ant_worker_lootless",
			"ant_soldier_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "lair_ant_miniboss", "lair_ant_miniboss_2" },
		exp = 300,
		id = "base_ant_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"ant_lair_boss_9",
			"ant_hunter_lootless",
			"ant_soldier_lootless",
			"ant_guard_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "lair_ant_miniboss", "lair_ant_miniboss_2" },
		exp = 400,
		id = "base_ant_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_4", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"ant_lair_boss_10",
			"ant_officer_lootless",
			"ant_guard_lootless",
			"ant_soldier_lootless",
			"ant_officer_lootless",
		},
		isInstantBattle = true,
	},
}