return {
  ruinList = {
    { 26, 10 },
    { 4, 10 },
    { 5, 10 },
    { 6, 10 },
    { 51, 10 },
    { 46, 10 },
    { 47, 10 },
    { 58, 10 },
  },
  houseChance = 0.6,
  roadList = {
    { 1, 10 },
    { 2, 10 },
    { 61, 2 },
    { 3, 10 },
    { 62, 3 },
  },
  houseList = {
    { 7, 10 },
    { 8, 10 },
    { 30, 10 },
    { 31, 10 },
    { 49, 10 },
    { 50, 10 },
    { 60, 10 },
  },
  locationWorthPart = 1.4,
  locationWorth = 80,
  roadUnblockChance = 0.75,
  cityList = {
    {
      size = { 0, 5 },
      typeTable = { 0, 0, 0 },
      groupList = {
        { "every_craft", 1 },
        { "every_hp", 1 },
        { "every_battle", 1 },
        { "every_rad", 1 },
        { "crater_polluted", 1 },
      },
    },
    {
      size = { 6, 7 },
      typeTable = { 1, 0, 0 },
      groupList = {
        { "enemy_base", 1 },
        { "every_craft", 1 },
        { "every_hp", 1 },
        { "every_battle", 1 },
        { "every_rad", 1 },
        { "crater_polluted", 1 },
      },
    },
    {
      size = { 8, 9 },
      typeTable = { 1, 1, 0 },
      groupList = {
        { "enemy_base", 1 },
        { "component", 1 },
        { "library", 1 },
        { "weapon", 1 },
        { "other", 1 },
        { "medicine", 1 },
        { "every_rad", 1 },
        { "crater_polluted", 1 },
        { "bomb", 1 },
      },
    },
    {
      size = { 10, 12 },
      typeTable = { 1, 1, 1 },
      groupList = {
        { "enemy_base", 2 },
        { "food", 1 },
        { "medicine", 1 },
        { "component", 2 },
        { "azs", 1 },
        { "library", 1 },
        { "weapon", 2 },
        { "other", 1 },
        { "every_rad", 2 },
        { "crater_polluted", 1 },
        { "bomb", 1 },
      },
    },
    {
      size = { 13, 15 },
      typeTable = { 2, 2, 1 },
      groupList = {
        { "enemy_base", 2 },
        { "food", 1 },
        { "medicine", 1 },
        { "component", 3 },
        { "azs", 1 },
        { "library", 1 },
        { "weapon", 2 },
        { "other", 2 },
        { "every_rad", 2 },
        { "crater_polluted", 1 },
        { "bomb", 1 },
      },
    },
    {
      size = { 16, 18 },
      typeTable = { 2, 2, 2 },
      groupList = {
        { "enemy_base", 3 },
        { "food", 1 },
        { "medicine", 1 },
        { "component", 4 },
        { "azs", 1 },
        { "library", 2 },
        { "weapon", 2 },
        { "other", 3 },
        { "every_rad", 2 },
        { "crater_polluted", 1 },
        { "bomb", 1 },
      },
    },
    {
      size = { 19, 30 },
      typeTable = { 4, 3, 2 },
      groupList = {
        { "enemy_base", 3 },
        { "food", 1 },
        { "medicine", 2 },
        { "component", 4 },
        { "azs", 1 },
        { "library", 2 },
        { "weapon", 3 },
        { "other", 3 },
        { "every_rad", 3 },
        { "crater_polluted", 1 },
        { "bomb", 1 },
      },
    },
  },
  groupTable = {
    medicine = {
      { 10, 10 },
      { 33, 20 },
      { 34, 40 },
    },
    weapon = {
      { 20, 10 },
      { 66, 10 },
      { 64, 10 },
      { 37, 30 },
      { 39, 60 },
    },
    bomb = {
      { 68, 10 },
    },
    crater_polluted = {
      { 27, 10 },
    },
    size3x3 = {
      { 39, 10 },
      { 45, 10 },
    },
    food = {
      { 19, 50 },
      { 21, 30 },
      { 12, 20 },
    },
    component = {
      { 9, 10 },
      { 15, 10 },
      { 22, 10 },
      { 24, 10 },
      { 29, 10 },
      { 48, 10 },
      { 23, 10 },
    },
    every_craft = {
      { 9, 10 },
      { 15, 10 },
      { 22, 10 },
      { 24, 10 },
      { 48, 10 },
      { 23, 10 },
      { 14, 10 },
    },
    library = {
      { 63, 10 },
      { 65, 10 },
      { 38, 20 },
      { 32, 20 },
      { 35, 40 },
    },
    every_hp = {
      { 19, 20 },
      { 18, 10 },
      { 66, 10 },
      { 59, 10 },
    },
    other = {
      { 11, 10 },
      { 16, 10 },
      { 17, 10 },
      { 18, 10 },
      { 25, 10 },
      { 59, 10 },
    },
    size3x2 = {
      { 34, 10 },
      { 35, 10 },
    },
    size2x2 = {
      { 29, 10 },
      { 38, 10 },
      { 32, 10 },
      { 44, 10 },
    },
    every_rad = {
      { 10, 20 },
      { 11, 20 },
      { 12, 10 },
      { 21, 20 },
      { 25, 20 },
    },
    enemy_base = {
      { 52, 10 },
      { 53, 10 },
      { 54, 10 },
      { 55, 10 },
      { 56, 10 },
      { 57, 10 },
      { 44, 10 },
      { 45, 10 },
    },
    azs = {
      { 14, 10 },
    },
    crater = {
      { 26, 10 },
    },
    every_battle = {
      { 20, 10 },
      { 64, 10 },
      { 17, 10 },
      { 63, 5 },
      { 65, 5 },
      { 16, 5 },
    },
  },
  roadQuarterChance = 0.1,
}