return {
  traderBuyMult = 1,
  healRadiationWorth = 50,
  trainKmPerHour = 15,
  wheelGuaranteedSpinBegins = {
    { 0, 0, 14, 97, 0, 0, 3 },
    { 0, 0, 14, 0, 47, 0, 3 },
    { 0, 0, 14, 0, 47, 0, 3 },
  },
  workshopRepairMult = 0.5,
  healMinWorth = 100,
  buyerItemList = {
    "children_toys",
    "jewelry",
    "kompot",
    "pepsicola",
    "milk",
    "vodka",
    "moonshine",
    "apple_brandy",
    "apple_wine",
    "apple_wine_I",
    "apple_wine_II",
    "apple_wine_III",
    "apple_wine_V",
    "apple_wine_X",
    "apple_wine_XL",
    "whiskey",
    "whiskey_I",
    "whiskey_II",
    "whiskey_III",
    "whiskey_V",
    "whiskey_X",
    "whiskey_XL",
    "wine",
    "champagne",
    "egg",
    "cheese",
    "vegetable",
    "apple",
    "corn",
    "potato",
    "mandarin",
    "marinated_vegetable",
    "jam",
    "stewed_meat",
    "porridge_can",
    "beef_can",
    "condensed_milk",
    "honey",
    "crumbs",
    "dryMeat",
    "fat",
    "salted_meat",
    "smoked_salo",
    "coffee",
    "tea",
    "sugar",
    "salt",
    "spice",
    "flour",
    "pasta",
    "buckwheat",
    "rice",
    "rat_meat",
    "snake_meat",
    "tough_meat",
    "fat_meat",
    "infected_meat",
    "mutant_meat",
    "salo",
    "lymph",
    "cigar",
    "sigaretes",
    "alcohol",
    "potion_energy",
    "potion_radiation",
    "medicine1",
    "medicine3",
    "medicine4",
    "medicine6",
    "medicine7",
    "medicine8",
    "medicine9",
    "penicillin",
    "water_pipe",
    "screw",
    "coil",
    "weapons_parts",
    "bicycle_part",
    "moto_part",
    "auto_part",
    "gas",
    "diesel",
    "small_engine",
    "armortile",
    "titan_ore",
    "titan",
    "aluminium",
    "steel",
    "iron",
    "tire",
    "welder_broken",
    "accumulator_broken",
    "soap",
    "capsule",
    "cement",
    "firebrick",
    "tape",
    "rubber_part",
    "cable",
    "sulfuric_acid",
    "electrodes",
    "gunpowder",
    "sulfur",
    "saltpeter",
    "lead",
    "oil",
    "string",
    "rags2",
    "provoloka",
    "nail",
    "rope",
    "spark_plug",
    "tanning_solution",
    "plastic_explosives",
    "furniture",
    "chitin",
    "animal_skin",
    "boiled_skin",
    "prepared_skin",
    "poison",
    "bone",
    "bone_glue",
    "fire_matches",
    "tt_ammo",
    "shotgun_ammo",
    "ak74_ammo",
    "mosin_ammo",
    "rpg7_ammo",
    "f_1",
    "flash_grenade",
    "cocktail_molotov",
    "gunpowder_grenade",
    "cockroach_corpse",
    "cockroach_m_corpse",
    "rat_corpse",
    "rad_rat_corpse",
    "rat_mutant_corpse",
    "lynx_corpse",
    "lynx_rabid_corpse",
    "rad_lynx_corpse",
    "lynx_mutant_corpse",
    "snake_corpse",
    "wolf_hungry_corpse",
    "wolf_corpse",
    "rad_wolf_corpse",
    "wolf_mutant_corpse",
    "boar_corpse",
    "boar_fat_corpse",
    "rad_boar_corpse",
    "boar_mutant_corpse",
    "bear_wounded_corpse",
    "bear_corpse",
    "rad_bear_corpse",
    "bear_mutant_corpse",
    "bear_mutant_strong_corpse",
    "ant_worker_corpse",
    "ant_soldier_corpse",
    "ant_hunter_corpse",
    "ant_guard_corpse",
    "ant_officer_corpse",
    "bee_worker_corpse",
    "bee_soldier_corpse",
    "bee_guard_corpse",
    "bee_mother_corpse",
    "bee_queen_corpse",
    "hedgehog_corpse",
    "turtle_corpse",
    "toad_corpse",
    "eagle_corpse",
    "centipede_corpse",
    "scorpion_corpse",
    "spider_corpse",
    "fish_corpse",
    "dog_corpse",
    "wasp_corpse",
    "hornet_corpse",
    "bee_queen_head",
    "wax",
    "copper_coin",
    "schoolbook",
    "dice",
    "dice_rare",
    "cards",
    "cards_rare",
    "watch",
    "watch_rare",
    "music_record",
    "guitar",
    "bayan",
    "piano",
    "turntable",
    "tv",
    "singer",
    "vacuum",
    "washer",
    "stove",
    "freezer",
    "samovar",
    "carpet",
    "armchair",
    "sofa",
    "bathtub",
    "mattress",
    "magazine",
    "electro_motor",
    "electro_motor_big",
    "drill_mill",
    "metal_lathe",
    "typewriter",
    "scales",
    "mirror",
    "metal_plate",
    "copper",
    "gold",
    "sandpaper",
    "rubber",
    "washing_powder",
    "electronic_part",
    "belomor",
    "chopmeat",
    "easter_egg_1",
    "easter_egg_2",
    "easter_egg_3",
    "easter_egg_4",
    "easter_egg_5"
  },
  buyerBuyStepList = { 5, 15, 25 },
  wheelAnimation = {
    {
      currencyObjCount = 40,
      awardTime = 3000,
    },
    {
      currencyObjCount = 50,
      awardTime = 3500,
    },
    {
      currencyObjCount = 60,
      awardTime = 4000,
    },
    {
      currencyObjCount = 200,
      awardTime = 8000,
    },
    {
      currencyObjCount = 160,
      awardTime = 7000,
    },
    {
      currencyObjCount = 90,
      awardTime = 5000,
    },
    {
      currencyObjCount = 80,
      awardTime = 4500,
    },
    {
      currencyObjCount = 120,
      awardTime = 6000,
    },
  },
  wheelGuaranteedSpin = {
    { 1000, 500, 15, 100, 50, 250, 5 },
    { 1000, 500, 15, 100, 50, 250, 5 },
  },
  trainMoveKgPrice = 0.00001,
  repairMinWorth = 5,
  timeQuestUpdate = 60,
  wheelSpinLimit = { 3, 5 },
  questCategoryLimit = {
    fight = 3,
    emba_doc_quest = 1,
    emba_dcomp_quest = 1,
    new_year_boss = 1,
    emba_bar_quest = 1,
    order = 1,
    supply = 1,
    halloween_boss = 1,
    travel = 2,
    emba_quest = 1,
  },
  trainMoveKmPrice = 0.2,
  wheelMultProbability = {
    { 1, 0.5 },
    { 2, 0.307 },
    { 3, 0.15 },
    { 5, 0.025 },
    { 10, 0.01 },
    { 20, 0.005 },
    { 30, 0.002 },
    { 50, 0.001 },
  },
  settlementAnalyticsQuestCategory = {
    "order",
    "emba_dcomp_quest",
    "travel",
    "fight",
    "base_quest",
    "emba_bar_quest"
  },
  playerQuestLimit = 21,
  traderCategoryAnalyticsTable = {
    tool = {
      itemList = {},
      tagList = {
        "axe_tag",
        "knife_tag",
        "pan_tag",
        "needle_tag",
        "tools_tag",
        "fire_source"
      },
    },
    search = {
      itemList = { "batteryaaa", "explosive_pack" },
      tagList = {
        "light",
        "hacksaw_tag",
        "crowbar_tag"
      },
    },
    ammo = {
      itemList = {
        "gunpowder_grenade",
        "cocktail_molotov",
        "flash_grenade",
        "f_1",
        "smoke_grenade"
      },
      tagList = { "ammo" },
    },
    other = {
      itemList = {},
      tagList = {},
    },
    fuel = {
      itemList = {},
      tagList = { "fuel_tag" },
    },
    radiation = {
      itemList = {
        "gasmask_filter",
        "medicine3",
        "potion_radiation",
        "vodka",
        "apple_brandy",
        "mixed_alcohol",
        "wine",
        "moonshine",
        "champagne"
      },
      tagList = { "breath" },
    },
    component = {
      itemList = { "alcohol" },
      tagList = { "category_component" },
    },
    food = {
      itemList = {},
      tagList = { "food", "drink" },
    },
  },
  questCategoryList = {
    "order",
    "travel",
    "fight",
    "base_quest",
    "winter_base_quest"
  },
  healHpWorth = 1,
  buyerCartProductLimit = 24,
  baseSpinworth = 250,
  buyerSellMult = 0.75,
  wheelRewardAngle = { 0, 90, 180, 45, 315, 135, 270, 225 },
  trainMapBaseTable = {
    base_krasnoyarsk = {
      y = 0.15,
      imageY = -0.2,
      x = 0.19,
    },
    base_omsk = {
      isTitleBottom = true,
      y = 0.08,
      imageY = 0.2,
      x = -0.118,
    },
    base_kurgan = {
      imageX = -0.03,
      isTitleBottom = true,
      y = -0.13,
      imageY = 0.2,
      x = -0.23,
    },
    base_novosibirsk = {
      y = 0.145,
      imageY = -0.2,
      x = 0.03,
    },
    base_chelyabinsk = {
      x = -0.3,
      y = -0.17,
      imageY = -0.08,
      imageX = -0.12,
    },
    base_tymen = {
      x = -0.2,
      y = -0.2,
      imageX = 0.08,
    },
    base_magnitogorsk = {
      imageX = -0.05,
      style = "SHK",
      imageWidth = 0.0,
      isTitleBottom = true,
      imageY = 0.18,
      y = -0.15,
      x = -0.35,
    },
    base_surgut = {
      style = "SHK",
      imageWidth = 0.0,
      imageX = 0.065,
      imageY = 0.055,
      y = -0.35,
      x = -0.05,
    },
    base_sverdlovsk = {
      style = "SHK",
      imageWidth = 0.0,
      imageX = 0.065,
      imageY = -0.075,
      y = -0.27,
      x = -0.27,
    },
    base_irkutsk = {
      y = 0.4,
      imageY = -0.2,
      x = 0.37,
    },
  },
  buyerItemWorthTable = {
    pm_ammo = 1,
  },
  wheelSpeed = 180,
  traderCartProductLimit = 24,
  timeSlotUpdate = 3600,
  baseResetPrice = { -1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1,-1 },
  traderBuyStepList = { 5, 150, 300 },
  baseTrainTable = {
    base_kurgan = { "base_tymen", "base_omsk" },
    base_chelyabinsk = { "base_kurgan" },
    base_krasnoyarsk = { "base_irkutsk" },
    base_omsk = { "base_novosibirsk" },
    base_novosibirsk = { "base_krasnoyarsk" },
  },
  currencyList = {
    "black_ruble",
    "iron_nut",
    "ration_card",
    "halloween_coin",
    "halloween_soul",
    "ny_balls",
    "ny_cookie",
    "emba_disk"
  },
  questTagLimit = {
    ally_item = 1,
    place_stash_item = 1,
    delivery_item = 1,
    catch_thief = 1,
    take_stash_item = 1,
    comrade = 1,
    construction_team = 1,
  },
  questCategoryOrder = {
    new_year_boss = 1,
    halloween_boss = 1,
  },
  timeTraderUpdate = 60,
  timeBuyerUpdate = 60,
  ignoredQuestLimitCategory = {
    "progress_quest",
    "halloween2022",
    "halloween2022_boss"
  },
  wheelGirlPhrases = {
    win2 = {
      strings.wheelGirl.win2[1],
      strings.wheelGirl.win2[2],
      strings.wheelGirl.win2[3],
      strings.wheelGirl.win2[4]
    },
    win5 = {
      strings.wheelGirl.win5[1],
      strings.wheelGirl.win5[2],
      strings.wheelGirl.win5[3]
    },
    win30 = { strings.wheelGirl.win30[1] },
    win20 = { strings.wheelGirl.win20[1], strings.wheelGirl.win20[2] },
    idle = {
      strings.wheelGirl.idle[1],
      strings.wheelGirl.idle[2],
      strings.wheelGirl.idle[3],
      strings.wheelGirl.idle[4]
    },
    win3 = {
      strings.wheelGirl.win3[1],
      strings.wheelGirl.win3[2],
      strings.wheelGirl.win3[3]
    },
    win50 = { strings.wheelGirl.win50[1], strings.wheelGirl.win50[2] },
    spin = {
      strings.wheelGirl.spin[1],
      strings.wheelGirl.spin[2],
      strings.wheelGirl.spin[3]
    },
    win10 = { strings.wheelGirl.win10[1] },
    win1 = {
      strings.wheelGirl.win1[1],
      strings.wheelGirl.win1[2],
      strings.wheelGirl.win1[3],
      strings.wheelGirl.win1[4]
    },
  },
  baseQuestLimit = 25,
  questDifficultyColor = {
    { 0.2, 0.8, 0.4 },
    { 0.8, 0.8, 0.2 },
    { 0.8, 0.2, 0.2 },
  },
  reputationList = { 0, 300, 800, 1550, 2500, 5000 },
  currencyWorth = {
    ration_card = 0.25,
    black_ruble = 0.5,
    ny_cookie = 1,
    halloween_coin = 1,
    halloween_soul = 1,
    ny_balls = 1,
    emba_disk = 1,
    iron_nut = 0.25,
  },
  wheelSpinPrices = {
    { 1, 100 },
    { 5, 500 },
    { 10, 1000 },
  },
  reputationText = {
    { "outsider" },
    { "newbie" },
    { "friend" },
    { "respected" },
    { "authority" },
    { "legend" },
  },
  traderCategoryAnalyticsList = {
    "ammo",
    "fuel",
    "tool",
    "search",
    "radiation",
    "food",
    "component",
    "other"
  },
}