return {
-- ===================== CUSTOM
	{
		id = "agw_arzacult",
		quantity = 1,
		itemWorth = 5000,
		reputationLevel = 4,
	},
	{
		id = "agw_sovauniform",
		quantity = 1,
		itemWorth = 5000,
		reputationLevel = 3,
	},
	{
		id = "agw_tankbrigade",
		quantity = 1,
		itemWorth = 5000,
		reputationLevel = 3,
	},
	{
		id = "agw_tank_round",
		quantity = 2,
		itemWorth = 20000,
		reputationLevel = 4,
	},
	{
		id = "agw_ap_ammo",
		quantity = 5,
		itemWorth = 1000,
		reputationLevel = 4,
	},
	
	-- {
	-- 	id = "",
	-- 	quantity = 10,
	-- 	itemWorth = 500,
	-- 	reputationLevel = 5,
	-- },
	-- {
	-- 	id = "",
	-- 	quantity = 10,
	-- 	itemWorth = 500,
	-- 	reputationLevel = 5,
	-- },
	-- {
	-- 	id = "",
	-- 	quantity = 10,
	-- 	itemWorth = 500,
	-- 	reputationLevel = 5,
	-- },

-- ===================== ORIG
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "respirator",
		reputationLevel = 2,
	},
	{
		quantity = 5,
		traderBuyMult = 1,
		id = "flashlight",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight1",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight2",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight6",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight5",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight4",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "flashlight3",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "military_clothes",
		itemWorth = 500,
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "military_armor",
		itemWorth = 1300,
		reputationLevel = 2,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "telega",
	},
	{
		id = "explosive_pack",
		quantity = 100,
	},
	{
		quantity = 20,
		traderBuyMult = 1,
		id = "batteryaaa",
	},
	{
		quantity = 10,
		traderBuyMult = 1,
		id = "gasmask_filter",
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "tt_ammo",
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "shotgun_ammo",
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "ak74_ammo",
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "mosin_ammo",
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "rpg7_ammo",
		reputationLevel = 1,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "f_1",
		reputationLevel = 1,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "flash_grenade",
		reputationLevel = 1,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "cocktail_molotov",
		reputationLevel = 1,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "gunpowder_grenade",
		reputationLevel = 1,
	},
	{
		quantity = 1000,
		traderBuyMult = 3,
		id = "gas",
		item = {
			"gas",
			1000,
		},
	},
	{
		quantity = 1000,
		traderBuyMult = 3,
		id = "diesel",
		item = {
			"diesel",
			1000,
		},
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "tape",
	},
	{
		quantity = 20,
		traderBuyMult = 2,
		id = "rope",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "trapie",
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "nail",
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "gunpowder",
		item = {
			"gunpowder",
			10,
		},
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "sulfur",
		item = {
			"sulfur",
			10,
		},
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "saltpeter",
		item = {
			"saltpeter",
			10,
		},
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "lead",
		item = {
			"lead",
			100,
		},
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "sugar",
	},
	{
		quantity = 20,
		traderBuyMult = 2,
		id = "bicycle_part",
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 3,
		id = "screw",
		reputationLevel = 2,
	},
	{
		quantity = 300,
		traderBuyMult = 2,
		id = "string",
	},
	{
		quantity = 500,
		traderBuyMult = 3,
		id = "capsule",
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 3,
		id = "oil",
		item = {
			"oil",
			10,
		},
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "provoloka",
	},
	{
		quantity = 20,
		traderBuyMult = 4,
		id = "coil",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 4,
		id = "washing_powder",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "rubber",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "soap",
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 2,
		id = "salt",
	},
	{
		quantity = 10,
		traderBuyMult = 3,
		id = "alcohol",
		reputationLevel = 2,
	},
	{
		quantity = 20,
		traderBuyMult = 2,
		id = "moto_part",
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "rubber_part",
		reputationLevel = 2,
	},
	{
		quantity = 10,
		traderBuyMult = 4,
		id = "spark_plug",
		reputationLevel = 2,
	},
	{
		quantity = 10,
		traderBuyMult = 4,
		id = "tire",
		reputationLevel = 2,
	},
	{
		quantity = 20,
		traderBuyMult = 4,
		id = "weapons_parts",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 4,
		id = "sandpaper",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "auto_part",
	},
	{
		quantity = 1,
		traderBuyMult = 4,
		id = "electro_motor",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 4,
		id = "bresent",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "electrodes",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "cable",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "sulfuric_acid",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "brick",
		item = {
			"brick",
			100,
		},
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "cement",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 5,
		id = "copper",
		reputationLevel = 2,
	},
	{
		quantity = 50,
		traderBuyMult = 4,
		id = "aluminium",
		reputationLevel = 2,
	},
	{
		quantity = 100,
		traderBuyMult = 2,
		id = "firebrick",
		item = {
			"firebrick",
			100,
		},
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "small_engine",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		id = "welder_broken",
		reputationLevel = 2,
	},
	{
		quantity = 3,
		id = "accumulator_broken",
		reputationLevel = 2,
	},
	{
		quantity = 500,
		id = "scrap_metal",
		item = {
			"scrap_metal",
			100,
		},
	},
	{
		id = "rags2",
		quantity = 100,
	},
	{
		quantity = 500,
		id = "iron",
		reputationLevel = 2,
	},
	{
		quantity = 500,
		traderBuyMult = 1,
		id = "wood",
		item = {
			"wood",
			10,
		},
	},
	{
		quantity = 500,
		traderBuyMult = 1,
		id = "coal",
		item = {
			"coal",
			10,
		},
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "spice",
	},
	{
		quantity = 1000,
		traderBuyMult = 1,
		id = "bottled_water",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "pepsicola",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "vodka",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "moonshine",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "egg",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "cheese",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "sausage",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "vegetable",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "apple",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "corn",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "potato",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "wheat",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "marinated_vegetable",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "jam",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "stewed_meat",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "porridge_can",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "beef_can",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "condensed_milk",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "honey",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "crumbs",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "dryFish",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "dryMeat",
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "pryanik",
	},
	{
		quantity = 10,
		traderBuyMult = 1.5,
		id = "egg_def1",
		item = {
			"egg",
			1,
		},
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "egg_def2",
		item = {
			"egg",
			1,
		},
	},
	{
		quantity = 5,
		traderBuyMult = 3,
		id = "egg_def3",
		item = {
			"egg",
			1,
		},
	},
	{
		quantity = 1000,
		traderBuyMult = 1,
		id = "bottled_water2",
		item = {
			"bottled_water",
			1,
		},
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "milk",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "wine",
	},
	{
		quantity = 30,
		traderBuyMult = 1,
		id = "champagne",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "apple_wine",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "whiskey",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "salo",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "fresh_fish",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "fat_meat",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "smoked_salo",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "coffee",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "tea",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "flour",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "pasta",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "buckwheat",
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "rice",
	},
	{
		id = "cigar",
		quantity = 20,
	},
	{
		quantity = 100,
		traderBuyMult = 1,
		id = "sigaretes",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "potion_energy",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "potion_radiation",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine1",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine3",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine4",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine6",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine7",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine8",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "medicine9",
		itemWorth = 110,
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "penicillin",
	},
	{
		quantity = 50,
		traderBuyMult = 1,
		id = "antirad",
	},
	{
		quantity = 50,
		traderBuyMult = 2,
		id = "fire_matches",
	},
	{
		quantity = 1,
		traderBuyMult = 2,
		id = "fishing_rod2",
	},
	{
		quantity = 1,
		traderBuyMult = 2,
		id = "lighter",
	},
	{
		quantity = 20,
		traderBuyMult = 1,
		id = "water_filter",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "knife",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "axe",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "instruments_kit2",
		reputationLevel = 2,
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "pan",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "iron_pot",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "breakage",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "shovel",
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "hacksaw",
		reputationLevel = 2,
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "instruments_kit",
		reputationLevel = 2,
	},
	{
		quantity = 5,
		traderBuyMult = 2,
		id = "instruments_kit3",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		reputationLevel = 2,
		id = "primus2",
		itemWorth = 1000,
	},
	{
		id = "blowtorch",
		quantity = 1,
	},
	{
		quantity = 1,
		id = "bag1",
		reputationLevel = 1,
	},
	{
		quantity = 1,
		id = "bag3",
		reputationLevel = 3,
	},
	{
		quantity = 1,
		traderBuyMult = 1,
		id = "mlp",
		reputationLevel = 2,
	},
	{
		quantity = 1,
		reputationLevel = 2,
		id = "hammer",
		itemWorth = 1250,
	},
	{
		quantity = 1,
		reputationLevel = 2,
		id = "mlp",
		itemWorth = 1200,
	},
	{
		quantity = 10,
		reputationLevel = 5,
		id = "minepass",
		itemWorth = 500,
	},
	{
		quantity = 3,
		traderBuyMult = 1,
		id = "gift_trade_ny2021",
		isNeedNewYear = true,
	},
}