return {
-- ============================== Orig	
	{
		hp = 500,
		name = strings.enemies.bandit.name,
		id = "bandit_test",
		armor = 100,
		dodgeChance = 0.5,
		iconLayer = {
			imageFile = "bandit7",
		},
		addTags = { "human_tag", "bandit_tag" },
		speed = 0,
		factionId = "bandit",
		bgLayer = {
			imageFile = "unit_bg3",
		},
		weaponList = {
			{
				damage = { 1, 2 },
				id = "pm",
				isPushback = false,
			},
		},
	},
	{
		loot = {
			{ "corpse_bandit9", 1 },
			{ "rpg7", 1 },
		},
		speed = 1,
		id = "bandit_rpg7",
		weaponList = {
			{
				id = "rpg7",
			},
		},
		template = "bandit",
		armor = 1500,
		immunityEffect = { "stuned" },
		iconLayer = {
			imageFile = "bandit/boss3",
		},
	},
	{
		hp = 100,
		id = "giga_bandit_steel_spear",
		isFreeAttack = true,
		armor = 4000,
		iconLayer = {
			imageFile = "bandit/m4",
		},
		template = "bandit",
		speed = 3,
		traitList = { "tank" },
		weaponList = {
			{
				id = "steel_spear_nopush",
				damage = { 210, 260 },
			},
		},
		perkList = {
			{
				id = "bloodrage",
			},
		},
	},
	{
		hp = 100,
		id = "giga_bandit_rifle",
		attackChance = 0.15,
		immunityEffect = { "stuned", "raven_distract" },
		isCounterAttack = true,
		iconLayer = {
			imageFile = "bandit/r2",
		},
		armor = 2100,
		template = "bandit",
		traitList = { "coward", "sniper" },
		weaponList = {
			{
				damage = { 200, 220 },
				id = "mosin",
				isArmorPiercing = false,
			},
		},
		speed = 3,
	},
	{
		hp = 100,
		id = "giga_bandit_svt",
		attackChance = 0.15,
		immunityEffect = { "stuned", "raven_distract" },
		isCounterAttack = true,
		iconLayer = {
			imageFile = "bandit/r3",
		},
		armor = 2150,
		template = "bandit",
		traitList = { "coward", "sniper" },
		weaponList = {
			{
				damage = { 210, 260 },
				id = "svt",
				isArmorPiercing = false,
			},
		},
		speed = 0,
	},
	{
		hp = 100,
		armor = 3000,
		id = "giga_bandit_mg",
		traitList = { "coward", "sniper" },
		template = "bandit",
		maxMove = 2,
		weaponList = {
			{
				id = "custom_mg",
				damage = { 160, 195 },
			},
		},
		iconLayer = {
			imageFile = "bandit/mg1",
		},
	},
	{
		hp = 100,
		armor = 3500,
		id = "giga_bandit_dp",
		traitList = { "coward", "sniper" },
		template = "bandit",
		speed = 2,
		weaponList = {
			{
				id = "dp",
				damage = { 210, 260 },
			},
		},
		iconLayer = {
			imageFile = "bandit/mg2",
		},
	},

-- ============================== Custom	
	{
		id = "agw_scamp_rpg7",
		hp = 100,
		speed = 0,
		armor = 2800,
		template = "bandit",
		immunityEffect = { "raven_distract" },
		iconLayer = {
			imageFile = "bandit/boss3",
		},
		loot = {
			{ "rpg7", 1 },
			{ "f_1", { 1, 6 } },
			{ "corpse_bandit9", 1 },
		},
		weaponList = {
			{
				id = "rpg7",
				damage = { 800, 1000 },
			},
			{
				id = "f_1",
				damage = { 100, 150 },
			},
		},
	},
	{
		id = "agw_scamp_heavy_sniper",
		hp = 100,
		speed = 0,
		armor = 1800,
		attackChance = 0.15,
		isCounterAttack = true,
		immunityEffect = { "stuned", "raven_distract" },
		template = "bandit",
		traitList = { "coward", "sniper" },
		iconLayer = {
			imageFile = "bandit/r4",
		},
		loot = {
			{ "svd", 1 },
			{ "mosin_short", { 0, 1 } },
			{ "agw_scamp_hsnip", 1 },
		},
		weaponList = {
			{
				id = "svd",
				damage = { 600, 710 },
				isArmorPiercing = false,
			},
			{
				id = "mosin_short",
				damage = { 200, 300 },
				isArmorPiercing = false,
			},
		},
	},
	{
		id = "agw_scamp_heavy_mg",
		hp = 100,
		armor = 4000,
		traitList = { "coward", "sniper" },
		template = "bandit",
		speed = 1,
		maxMove = 2,
		iconLayer = {
			imageFile = "bandit/boss2",
		},
		loot = {			
			{ "pk", 1 },
			{ "aks74u", { 0, 1 } },
			{ "agw_scamp_hmg", 1 },
		},
		weaponList = {
			{
				id = "pk",
				damage = { 1000, 1200 },
			},
			{
				id = "aks74u",
				damage = { 210, 280 },
			},
		},
	},
	{
		id = "agw_scamp_tank",
		name = "Tank",
		hp = 50,
		speed = 1,
		maxMove = 1,
		armor = 15000,
		attackChance = 0.10,
		missChance = 0.60,
		traitList = { "tank" },
		template = "bandit",
		-- loot = {
		-- 	{ "agw_broken_t72", 1 },
		-- 	{ "agw_tank_round", {3, 10} },
		-- },
		resistTable = {
      		fire_tag = -0.2,
      		grenade_tag = 0.4,
      		anti_tank = -0.9,
      		firearm_tag = 1
    	},
		weaponList = {
			{
				id = "agw_tank_gun",
				damage = { 1500, 4000 },
			},
			{
				id = "pk",
				damage = { 800, 1400 },
			},
		},
		iconLayer = {
			imageFile = "bandit/agw_tank",
		},
		immunityEffect = {
			"bleeding",
			"bleeding2",
			"burning2",
			"burning3",
			"burning4",
			"poison",
			"poison_weapon",
			"poison_weapon2",
			"poison_weapon3",
			"poison_weapon4",
			"poison_weapon5",
			"freezed",
			"slowed",
			"snow_slowed",
			"snow_speed",
			"stuned",
			"inaction",
			"blindness",
			"trap",
			"stake_pit",
			"web",
			"angry_bees",
			"raven_distract",
			"raven_blindness",
			"wolf_hold",
			"wolf_provoke",
			"polar_fox_debuff",
			"charm",
			"charm_dollar",
			"debuff_resist_vam",
			"fear",
			"curse",
			"possessed",
			"deadman_touch",
			"vulnerability",
			"star_blindness",
			"star_blindness2",
			"microbes",
			"bee_mother_wax",
			"sleep",
			"slowed_madman_big",
			"slowed_queen",
			"spore_infection",
			"red_flower_infection",
			"slowed_turret",
			"electro_stunned",
			"worm_infection",
			"spore_shield",
			"resist_range_debuff",
			"spore_regen",
			"speed_mad",
			"buff_mad",
			"slowed_endless",
			"buff_damage",
			"buff_speed",
			"buff_resist",
			"sleep_halloween",
			"plague",
			"plague_cauldron",
			"buff_zombie",
			"buff_damage_frankenstein",
			"buff_frankenstein",
			"plague_reaper",
			"fear_player",
			"electrogun_damage",
			"electrogun_resist",
			"quest_buff_speed",
			"quest_buff_range",
			"quest_buff_resist",
			"quest_buff_fly",
			"quest_buff_luck",
			"quest_debuff_curse",
			"quest_buff_regen",
			"quest_debuff_damage",
			"block_attack",
			-- "invincible",
			"ice_cream_effect",
			"possessed_civil",
			"vulnerability_endless",
			"resistance_endless",
			-- "invincible_stack",
			"weapon_resistance",
			"ny_boss6_buff2",
			"ny_boss6_buff3",
			"ny_boss6_buff4",
			"ny_boss6_buff5",
			"ny_boss6_buff6",
			"ny_boss6_buff7",
			"ny_boss6_buff8",
			"ny_boss6_buff9",
			"ny_boss6_protection",
			"brain_damage_low",
			"brain_damage_mushrom",
			"brain_damage",
			"brain_damage_boss4",
			"brain_damage_fake",
			"quest_target_fake",
			"secret_debuff",
			"frozen_slowed",
			"frosthorn_damage",
			"launcher_rad",
			"hack_range",
			"cyber_resist",
			"hack_disarm",
			-- "invincible_stack"
			"trap_burning",
		},
	},
}