return {
-- ================== test	
	{
		loot = {},
		exp = 150,
		name = strings.snowmen,
		list = {
			"bandit_nagant",
			"bandit_pps",
			"bandit_dog",
		},
		id = "bandit_level_test",
		template = "snowmen",
	},

-- ================== orig	
	{
		mapId = { "bandit_base_miniboss_1", "base_restaurant_6", "base_restaurant_7" },
		exp = 60,
		id = "base_bandit_5",
		isInstantBattle = true,
		list = {
			"base_restaurant_5",
			"bandit_rifle_5",
			"bandit_rifle_5",
			"bandit_shotgun_lootless",
			"bandit_nagant_lootless",
		},
		isFixedPosition = true,
	},
	{
		mapId = { "bandit_base_miniboss_1", "base_restaurant_6", "base_restaurant_7" },
		exp = 100,
		id = "base_bandit_6",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"base_restaurant_6",
			"bandit_rifle_6",
			"bandit_rifle_6",
			"bandit_pps_lootless",
			"bandit_grenade_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "bandit_base_miniboss_1", "base_restaurant_6", "base_restaurant_7" },
		exp = 160,
		id = "base_bandit_7",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_3", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"base_restaurant_7",
			"bandit_rifle_7",
			"bandit_rifle_7",
			"bandit_pps_lootless",
			"bandit_grenade_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "bandit_base_miniboss_2", "base_restaurant_6", "base_restaurant_7" },
		exp = 250,
		id = "base_bandit_8",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_1", 1 },
		},
		list = {
			"base_restaurant_8",
			"bandit_rifle_8",
			"bandit_rifle_8",
			"bandit_aks74u_8",
			"bandit_aks74u_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "bandit_base_miniboss_2", "base_restaurant_6", "base_restaurant_7" },
		exp = 300,
		id = "base_bandit_9",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9",
			"bandit_rifle_9",
			"bandit_ak74_9",
			"bandit_mg_9",
		},
		isInstantBattle = true,
	},
	{
		mapId = { "bandit_base_miniboss_2", "base_restaurant_6", "base_restaurant_7" },
		exp = 400,
		id = "base_bandit_10",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_restaurant_10",
			"bandit_rifle_10",
			"bandit_rifle_10",
			"bandit_ak74_9",
			"bandit_ak74_9",
			"bandit_steel_spear_lootless",
			"bandit_steel_spear_lootless",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_cantina",
		exp = 100,
		id = "bandit_construct_6_cantina",
		isInstantBattle = true,
		list = {
			"base_restaurant_6",
			"bandit_rifle_6_nofree",
			"bandit_rifle_6_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_6",
		},
		isFixedPosition = true,
	},
	{
		mapId = "bandit_construct_lair",
		exp = 100,
		id = "bandit_construct_6_lair",
		isInstantBattle = true,
		list = {
			"base_restaurant_6",
			"bandit_rifle_6_nofree",
			"bandit_rifle_6_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_6",
		},
		isFixedPosition = true,
	},
	{
		mapId = "bandit_construct_stockpile",
		exp = 100,
		id = "bandit_construct_6_stockpile",
		isInstantBattle = true,
		list = {
			"base_restaurant_6",
			"bandit_rifle_6_nofree",
			"bandit_rifle_6_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_6",
		},
		isFixedPosition = true,
	},
	{
		mapId = "bandit_construct_workshop",
		exp = 100,
		id = "bandit_construct_6_workshop",
		isInstantBattle = true,
		list = {
			"base_restaurant_6",
			"bandit_rifle_6_nofree",
			"bandit_rifle_6_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_6",
		},
		isFixedPosition = true,
	},
	{
		mapId = "bandit_construct_cantina",
		exp = 160,
		id = "bandit_construct_7_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"base_restaurant_7",
			"bandit_rifle_7_nofree",
			"bandit_rifle_7_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_lair",
		exp = 160,
		id = "bandit_construct_7_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"base_restaurant_7",
			"bandit_rifle_7_nofree",
			"bandit_rifle_7_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_stockpile",
		exp = 160,
		id = "bandit_construct_7_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"base_restaurant_7",
			"bandit_rifle_7_nofree",
			"bandit_rifle_7_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_workshop",
		exp = 160,
		id = "bandit_construct_7_workshop",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
		},
		list = {
			"base_restaurant_7",
			"bandit_rifle_7_nofree",
			"bandit_rifle_7_nofree",
			"bandit_pps_lootless",
			"bandit_grenade_6",
			"bandit_crossbow3_7",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_cantina",
		exp = 250,
		id = "bandit_construct_8_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"base_restaurant_8",
			"bandit_rifle_8_nofree",
			"bandit_rifle_8_nofree",
			"bandit_aks74u_8",
			"bandit_aks74u_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_lair",
		exp = 250,
		id = "bandit_construct_8_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"base_restaurant_8",
			"bandit_rifle_8_nofree",
			"bandit_rifle_8_nofree",
			"bandit_aks74u_8",
			"bandit_aks74u_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_stockpile",
		exp = 250,
		id = "bandit_construct_8_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"base_restaurant_8",
			"bandit_rifle_8_nofree",
			"bandit_rifle_8_nofree",
			"bandit_aks74u_8",
			"bandit_aks74u_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_workshop",
		exp = 250,
		id = "bandit_construct_8_workshop",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_5", 1 },
		},
		list = {
			"base_restaurant_8",
			"bandit_rifle_8_nofree",
			"bandit_rifle_8_nofree",
			"bandit_aks74u_8",
			"bandit_aks74u_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_cantina",
		exp = 300,
		id = "bandit_construct_9_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_lair",
		exp = 300,
		id = "bandit_construct_9_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_stockpile",
		exp = 300,
		id = "bandit_construct_9_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_workshop",
		exp = 300,
		id = "bandit_construct_9_workshop",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_cantina",
		exp = 400,
		id = "bandit_construct_10_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_10",
			"bandit_rifle_10_nofree",
			"bandit_rifle_10_nofree",
			"bandit_ak74_9",
			"bandit_ak74_9",
			"bandit_steel_spear_10",
			"bandit_steel_spear_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_lair",
		exp = 400,
		id = "bandit_construct_10_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_10",
			"bandit_rifle_10_nofree",
			"bandit_rifle_10_nofree",
			"bandit_ak74_9",
			"bandit_ak74_9",
			"bandit_steel_spear_10",
			"bandit_steel_spear_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_stockpile",
		exp = 400,
		id = "bandit_construct_10_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_10",
			"bandit_rifle_10_nofree",
			"bandit_rifle_10_nofree",
			"bandit_ak74_9",
			"bandit_ak74_9",
			"bandit_steel_spear_10",
			"bandit_steel_spear_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_construct_workshop",
		exp = 400,
		id = "bandit_construct_10_workshop",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_1", 1 },
			{ "miniboss_chest_2", 1 },
			{ "miniboss_chest_5", 1 },
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_10",
			"bandit_rifle_10_nofree",
			"bandit_rifle_10_nofree",
			"bandit_ak74_9",
			"bandit_ak74_9",
			"bandit_steel_spear_10",
			"bandit_steel_spear_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_cantina",
		exp = 300,
		id = "bandit_military_9_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_lair",
		exp = 300,
		id = "bandit_military_9_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_stockpile",
		exp = 300,
		id = "bandit_military_9_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_forge",
		exp = 300,
		id = "bandit_military_9_forge",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_gates",
		exp = 300,
		id = "bandit_military_9_gates",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_garage",
		exp = 300,
		id = "bandit_military_9_garage",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_barracks",
		exp = 300,
		id = "bandit_military_9_barracks",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_arena",
		exp = 300,
		id = "bandit_military_9_arena",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"bandit_ak74_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_iron_spear_8",
			"bear_mutant_strong_military_9",
			"bear_mutant_strong_military_9",
			"bandit_mg_9",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_medical",
		exp = 300,
		id = "bandit_military_9_medical",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
		},
		list = {
			"base_restaurant_9",
			"bandit_rifle_9_nofree",
			"bandit_rifle_9_nofree",
			"bandit_ak74_9",
			"bandit_mg_9",
			"bandit_iron_spear_8",
			"bandit_iron_spear_8",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_cantina",
		exp = 400,
		id = "bandit_military_10_cantina",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_lair",
		exp = 400,
		id = "bandit_military_10_lair",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_stockpile",
		exp = 400,
		id = "bandit_military_10_stockpile",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_forge",
		exp = 400,
		id = "bandit_military_10_forge",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_gates",
		exp = 400,
		id = "bandit_military_10_gates",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_garage",
		exp = 400,
		id = "bandit_military_10_garage",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_barracks",
		exp = 400,
		id = "bandit_military_10_barracks",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_arena",
		exp = 400,
		id = "bandit_military_10_arena",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"bandit_dp_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_steel_spear_10_military",
			"bear_mutant_strong_military_9",
			"bear_mutant_strong_military_9",
			"bandit_dp_10",
		},
		isInstantBattle = true,
	},
	{
		mapId = "bandit_military_medical",
		exp = 400,
		id = "bandit_military_10_medical",
		isFixedPosition = true,
		loot = {
			{ "miniboss_chest_6", 1 },
			{ "miniboss_chest_4", 1 },
		},
		list = {
			"base_military_10",
			"bandit_rifle_10_military",
			"bandit_rifle_10_military",
			"bandit_dp_10",
			"bandit_dp_10",
			"bandit_steel_spear_10_military",
			"bandit_steel_spear_10_military",
		},
		isInstantBattle = true,
	},

-- ================== Scamp	
	{
		mapId = "bandit_world_hell",
		exp = 400,
		id = "bandit_hell",
		isInstantBattle = true,
		list = {
			"giga_bandit_svt",
			"giga_bandit_svt",
			"giga_bandit_svt",
			"giga_bandit_steel_spear",
			"giga_bandit_steel_spear",
			"giga_bandit_rifle",
			"giga_bandit_mg",
			"giga_bandit_mg",
			"giga_bandit_dp",
		},
		isFixedPosition = true,
	},

-- ==================================== Custom
	{
		id = "agw_scamp_tank",
		mapId = "agw_bandit_scamp_map",
		exp = 50000,
		isInstantBattle = true,
		isFixedPosition = true,
		list = {
			"agw_scamp_heavy_sniper",
			"agw_scamp_rpg7",
			"agw_scamp_heavy_sniper",
			"giga_bandit_steel_spear",
			"giga_bandit_dp",
			"agw_scamp_heavy_sniper",
			"agw_scamp_heavy_mg",
			"agw_scamp_heavy_mg",
			"agw_scamp_heavy_mg",
			"agw_scamp_tank",
		},
	},
-- Name : x, y
-- "agw_scamp_heavy_sniper"			:{ 2, 5 },
-- "agw_scamp_rpg7"					:{ 7, 4 },
-- "agw_scamp_heavy_sniper"			:{ 9, 2 },
-- "giga_bandit_steel_spear"		:{ 2, 7 },
-- "giga_bandit_dp"					:{ 8, 7 },
-- "agw_scamp_heavy_sniper"			:{ 3, 2 },
-- "agw_scamp_heavy_mg"				:{ 5, 5 },
-- "agw_scamp_heavy_mg"				:{ 7, 2 },
-- "agw_scamp_heavy_mg"				:{ 5, 1 },
-- "agw_tank_bandit"				:{ 4, 4 },

-- ================== 




-- ================== 
-- ================== 
}