return {
-- ============= Custom
	{
		id = "agw_base_arkhangelsk",
		x = 4.04919,
		y = 2.89582,
		-- x = 4.4100,
		-- y = 1.6500,
		size = 0.01,
		baseId = "agw_arkhangelsk_base",
		bannerFile = "agw_arkhangelsk",
		analyticId = "agw_arkhangelsk_base",
	},
	{
		id = "agw_base_pevek",
		x = 13.22987,
		y = 1.49818,
		-- x = 4.4150,
		-- y = 1.6400,
		size = 0.01,
		baseId = "agw_pevek_base",
		bannerFile = "agw_pevek",
		analyticId = "agw_pevek_base",
	},
	{
		id = "agw_base_tiksi",
		x = 10.78612,
		y = 3.22078,
		-- x = 4.4200,
		-- y = 1.6400,
		size = 0.01,
		baseId = "agw_tiksi_base",
		bannerFile = "agw_tiksi",
		analyticId = "agw_tiksi_base",
	},
	{
		id = "agw_base_vladivostok",
		x = 13.66329,
		y = 8.80972,
		-- x = 4.4250,
		-- y = 1.6400,
		size = 0.01,
		baseId = "agw_vladivostok_base",
		bannerFile = "agw_vladivostok",
		analyticId = "agw_vladivostok_base",
	},
	{
		id = "agw_base_yakutsk",
		x = 11.74294,
		y = 5.04001,
		-- x = 4.4300,
		-- y = 1.6400,
		size = 0.01,
		baseId = "agw_yakutsk_base",
		bannerFile = "agw_yakutsk",
		analyticId = "agw_yakutsk_base",
	},
	{
		id = "agw_base_skyt",
		x = 4.28449,
		y = 3.97663,
		-- x = 4.4350,
		-- y = 1.6400,
		size = 0.01,
		baseId = "agw_skyt_base",
		bannerFile = "agw_skyt",
		analyticId = "agw_skyt_base",
	},



-- ============= ORIG
	{
		bannerFile = "chelyabinsk",
		x = 4.34586,
		y = 5.91009,
		baseId = "base_chelyabinsk",
		id = "chelyabinsk_base",
		analyticId = "base_chelyabinsk",
	},
	{
		bannerFile = "sverdlovsk",
		x = 4.45233,
		y = 5.55389,
		baseId = "base_sverdlovsk",
		id = "base4",
		analyticId = "base_sverdlovsk",
	},
	{
		bannerFile = "magnitogorsk",
		x = 3.93886,
		y = 6.03475,
		baseId = "base_magnitogorsk",
		id = "base2",
		analyticId = "base_magnitogorsk",
	},
	{
		bannerFile = "novosibirsk",
		x = 6.79461,
		y = 6.96955,
		baseId = "base_novosibirsk",
		id = "novosibirsk_base",
		analyticId = "base_novosibirsk",
	},
	{
		bannerFile = "krasnoyarsk",
		x = 7.9424,
		y = 6.98067,
		baseId = "base_krasnoyarsk",
		id = "krasnoyarsk_base",
		analyticId = "base_krasnoyarsk",
	},
	{
		bannerFile = "irkutsk",
		x = 9.38922,
		y = 7.81255,
		baseId = "base_irkutsk",
		id = "irkutsk_base",
		analyticId = "base_irkutsk",
	},
	{
		bannerFile = "omsk",
		x = 5.6395,
		y = 6.66374,
		baseId = "base_omsk",
		id = "omsk_base",
		analyticId = "base_omsk",
	},
	{
		bannerFile = "tymen",
		x = 5.03069,
		y = 5.74932,
		baseId = "base_tymen",
		id = "tymen_base",
		analyticId = "base_tymen",
	},
	{
		bannerFile = "kurgan",
		x = 4.7873,
		y = 6.05648,
		baseId = "base_kurgan",
		id = "kurgan_base",
		analyticId = "base_kurgan",
	},
	{
		bannerFile = "surgut",
		x = 6.14299,
		y = 5.3497,
		baseId = "base_surgut",
		id = "surgut_base",
		analyticId = "base_surgut",
	},
	{
		bannerFile = "tula",
		x = 2.0695,
		y = 4.0545,
		baseId = "base_tula",
		id = "tula_base",
		analyticId = "base_tula",
	},
	{
		bannerFile = "voronej",
		x = 1.7569,
		y = 4.5565,
		baseId = "base_voronej",
		id = "voronej_base",
		analyticId = "base_voronej",
	},
	{
		bannerFile = "rostov",
		x = 1.0904,
		y = 5.1864,
		baseId = "base_rostov",
		id = "rostov_base",
		analyticId = "base_rostov",
	},
	{
		bannerFile = "arzamas",
		x = 2.7748,
		y = 4.48,
		baseId = "base_arzamas",
		id = "arzamas_base",
		analyticId = "base_arzamas",
	},
	{
		bannerFile = "ryazan",
		x = 2.2536,
		y = 4.1943,
		baseId = "base_ryazan",
		id = "ryazan_base",
		analyticId = "base_ryazan",
	},
	{
		bannerFile = "izhevsk",
		x = 3.7424,
		y = 5.0242,
		baseId = "base_izhevsk",
		id = "izhevsk_base",
		analyticId = "base_izhevsk",
	},
	{
		bannerFile = "olonec",
		x = 2.9475,
		y = 2.7303,
		baseId = "base_olonec",
		id = "base_olonec",
		analyticId = "base_olonec",
	},
	{
		bannerFile = "leningrad",
		x = 2.655,
		y = 2.7169,
		baseId = "base_leningrad",
		id = "base_leningrad",
		analyticId = "base_leningrad",
	},
	{
		bannerFile = "tver",
		x = 2.3975,
		y = 3.5157,
		baseId = "base_tver",
		id = "tver_base",
		analyticId = "base_tver",
	},
	{
		id = "briansk_base",
		bannerFile = "briansk",
		x = 1.6817,
		y = 3.8235,
		baseId = "base_briansk",
		analyticId = "base_briansk",
	},
	{
		id = "gorenichi_base",
		bannerFile = "kiev",
		x = 0.8213,
		y = 3.7259,
		baseId = "base_gorenichi",
		analyticId = "base_kiev",
	},
	{
		id = "stepnoj_base",
		size = 0.0075,
		x = 7.2264,
		y = 7.303,
		bannerFile = "stepnoj",
		storyId = "sasha",
		notDropItem = true,
		baseId = "base_stepnoj",
		needQuestState = {
			{
				"familyMatters",
				20,
				">=",
			},
			{
				"familyMatters",
				30,
				"<=",
			},
		},
	},
}