return {
-- ======================= Custom
	{
		id = "agw_mauser_c96",
		spendTime = 60,
		itemWorth = 550,
		sound = "craft",
		item = { "mauser", 1 },
		need = {
			{ "oil", 120 },
			{ "screw", 5 },
			{ "coil", 4 },
			{ "weapons_parts", 9 },
			{ "aluminium", 7 },
			{ "wood", 1 },
			{ "scrap_metal", 25 },
		},
	},
	{
		id = "explosive_big",
		spendTime = 30,
		itemWorth = 100,
		sound = "craft",
		item = { "explosive_big", 1 },
		need = {
			{ "explosive_pack", 9 },
			{ "provoloka", 6 },
			{ "batteryaaa", 2 },
		},
	},
	{
		id = "explosive_pack",
		spendTime = 15,
		itemWorth = 50,
		sound = "craft",
		item = { "explosive_pack", 1 },
		need = {
			{ "plastic_explosives", 4 },
			{ "provoloka", 4 },
			{ "batteryaaa", 2 },			
		},
	},
	{
		id = "racer_bat",
		spendTime = 10,
		itemWorth = 50,
		sound = "craft",
		item = { "racer_bat", 1 },
		need = {
			{ "wood", 1 },
			{ "nail", 15 },
		},
	},
	{
		id = "mlp",
		spendTime = 60,
		itemWorth = 500,
		sound = "craft",
		item = { "mlp", 1 },
		need = {
			{ "steel", 4 },
			{ "wood", 1 },
			{ "iron", 4 },
		},
	},
	{
		id = "hammer",
		spendTime = 60,
		itemWorth = 100,
		sound = "craft",
		item = { "hammer", 1 },
		need = {
			{ "steel", 8 },
			{ "iron", 2 },			
		},
	},
	{
		id = "agw_ptrd",
		spendTime = 60,
		itemWorth = 2500,
		sound = "craft",
		item = { "agw_ptrd", 1 },
		need = {
			{ "oil", 500 },
			{ "screw", 15 },
			{ "coil", 10 },
			{ "weapons_parts", 12 },
			{ "iron", 15 },
			{ "steel", 20 },
			{ "titan", 15 },
			{ "scrap_metal", 55 },
		},
	},
	{
		id = "agw_tank_round",
		spendTime = 120,
		itemWorth = 1500,
		sound = "craft",
		item = { "agw_tank_round", 1 },
		need = {
			{ "agw_tank_shell", 1 },
			{ "gunpowder", 250 },
			{ "steel", 20 },
			{ "plastic_explosives", 5 },
			{ "capsule", 1 },
		},
	},
	{
		id = "beef_can",
		spendTime = 30,
		itemWorth = 20,
		sound = "craft",
		item = { "beef_can", 1 },
		need = {
			{ "chopmeat", 10 },
			{ "iron", 4 },
		},
	},
	{
		id = "chopper",
		spendTime = 30,
		itemWorth = 20,
		sound = "craft",
		item = { "chopper", 1 },
		need = {			
			{ "moto_part", 25, true },
			{ "tape", 15, true },
			{ "provoloka", 20, true },
			{ "oil", 200, true },
			{ "screw", 10, true },
			{ "tire", 3, true },
			{ "spark_plug", 2, true },
			{ "rubber_part", 8, true },
			{ "tools_tag", 1 },
		},

	},
	-- {
	-- 	id = "agw_mi24_missile",
	-- 	spendTime = 60,
	-- 	itemWorth = 550,
	-- 	sound = "craft",
	-- 	item = { "agw_mi24_missile", 1 },
	-- 	need = {
	-- 		{ "agw_tank_shell", 1 },
	-- 		{ "gunpowder", 250 },
	-- 		{ "steel", 20 },
	-- 		{ "plastic_explosives", 5 },
	-- 		{ "capsule", 1 },
	-- 	},
	-- },

	-- Armor
	{
		id = "agw_doncoss",
		spendTime = 60,
		itemWorth = 1500,
		sound = "craft",
		item = { "agw_doncoss", 1 },
		need = {
			{ "military_clothes", 1, true },
			{ "rags2", 20, true },
			{ "string", 50, true },
			{ "boiled_skin", 20, true }
		},
	},
	{
		id = "agw_ifgguard",
		spendTime = 60,
		itemWorth = 4500,
		sound = "craft",
		item = { "agw_ifgguard", 1 },
		need = {		
			{ "titan", 35 },
			{ "prepared_skin", 25 },
			{ "copper", 5 },
			{ "bresent", 8 },
			{ "rubber", 10 },
		},
	},
	{
		id = "agw_beekeeper",
		spendTime = 60,
		itemWorth = 1500,
		sound = "craft",
		item = { "agw_beekeeper", 1 },
		need = {
			{ "chitin_armor", 1, true },
			{ "gasmask1", 1, true },
			{ "military_clothes2", 1, true },
			{ "ozk", 1, true },
			{ "rags2", 15, true },
		},
	},
	{
		id = "agw_ossecurity",
		spendTime = 60,
		itemWorth = 4500,
		sound = "craft",
		item = { "agw_ossecurity", 1 },
		need = {
			{ "prepared_skin", 15, true },
			{ "armortile", 20, true },
			{ "steel", 20, true },
			{ "aluminium", 50, true },
			{ "rubber", 15, true },
		},
	},
	{
		id = "agw_olonfisherman",
		spendTime = 60,
		itemWorth = 1500,
		sound = "craft",
		item = { "agw_olonfisherman", 1 },
		need = {
			{ "handmade_clothes", 1, true },
			{ "fishing_rod", 1, true },
			{ "scrap_metal", 20, true },
			{ "trapie", 20, true },
		},
	},
	{
		id = "agw_ryzaraider",
		spendTime = 60,
		itemWorth = 1550,
		sound = "craft",
		item = { "agw_ryzaraider", 1 },
		need = {

			{ "motorway_armor", 1, true },
			{ "tire", 2, true },
			{ "prepared_skin", 10, true },
			{ "metal_plate", 20, true },
		},
	},
	{
		id = "agw_sovafield",
		spendTime = 60,
		itemWorth = 5500,
		sound = "craft",
		item = { "agw_sovafield", 1 },
		need = {
			{ "ceramic_vest", 1, true },
			{ "military_armor", 1, true },
			{ "gasmask_sova", 1, true },
			{ "electronic_part", 15, true },
			{ "steel", 50, true },
			{ "prepared_skin", 30, true },
			{ "armortile", 20, true },
		},
	},
	{
		id = "agw_touristsuit",
		spendTime = 60,
		itemWorth = 550,
		sound = "craft",
		item = { "agw_touristsuit", 1 },
		need = {
			{ "gasmask1", 1, true },
			{ "metal_plate", 20, true },
			{ "military_clothes2", 1, true },
			{ "boiled_skin", 30, true },
			{ "rags2", 15, true },
			{ "string", 50, true },
		},
	},
	{
		id = "agw_vdvfield",
		spendTime = 60,
		itemWorth = 2500,
		sound = "craft",
		item = { "agw_vdvfield", 1 },
		need = {
			{ "mlp", 1, true },
			{ "rags2", 20, true },
			{ "military_clothes2", 1, true },
			{ "prepared_skin", 30, true },
			{ "rope", 5, true },
			{ "rubber", 10, true },
			{ "aluminium", 40, true },
			{ "string", 50, true },
		},
	},

-- ======================= Orig
	{
		id = "gasmask1",
		item = { "gasmask1", 1 },
		need = {
			{ "rubber", 1 },
			{ "tape", 1 },
			{ "provoloka", 1 },
			{ "gasmask_filter", 1 },
		},
		itemWorth = 20,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask_mm",
		item = { "gasmask_mm", 1 },
		need = {
			{ "rubber", 2 },
			{ "tape", 2 },
			{ "provoloka", 2 },
			{ "gasmask_filter", 1 },
		},
		itemWorth = 120,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask2",
		item = { "gasmask2", 1 },
		need = {
			{ "rubber", 2 },
			{ "metal_plate", 2 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 1 },
		},
		itemWorth = 210,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask3",
		item = { "gasmask3", 1 },
		need = {
			{ "rubber", 3 },
			{ "aluminium", 2 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 1 },
		},
		itemWorth = 350,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask4",
		item = { "gasmask4", 1 },
		need = {
			{ "rubber", 3 },
			{ "prepared_skin", 2 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 1 },
		},
		itemWorth = 350,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask_iron",
		item = { "gasmask_iron", 1 },
		need = {
			{ "rubber", 4 },
			{ "iron", 10 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 2 },
		},
		itemWorth = 150,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask_oil",
		item = { "gasmask_oil", 1 },
		need = {
			{ "rubber", 4 },
			{ "steel", 2 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 2 },
		},
		itemWorth = 260,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "gasmask_sova",
		item = { "gasmask_sova", 1 },
		need = {
			{ "rubber", 4 },
			{ "electronic_part", 2 },
			{ "provoloka", 3 },
			{ "gasmask_filter", 2 },
		},
		itemWorth = 300,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "tt_ammo",
		item = { "tt_ammo", 1 },
		need = {
			{ "lead", 2 },
			{ "gunpowder", 1 },
			{ "scrap_metal", 1 },
		},
		itemWorth = 4,
		sound = "craft",
		spendTime = 10,
	},
	{
		id = "shotgun_ammo",
		item = { "shotgun_ammo", 1 },
		need = {
			{ "lead", 20 },
			{ "gunpowder", 9 },
			{ "glue_tag", 1 },
			{ "scrap_metal", 1 },
		},
		itemWorth = 5,
		sound = "craft",
		spendTime = 10,
	},
	{
		id = "mosin_ammo",
		item = { "mosin_ammo", 1 },
		need = {
			{ "lead", 20 },
			{ "gunpowder", 9 },
			{ "glue_tag", 1 },
			{ "scrap_metal", 1 },
		},
		itemWorth = 5,
		sound = "craft",
		spendTime = 10,
	},
	{
		id = "ak74_ammo",
		item = { "ak74_ammo", 1 },
		need = {
			{ "lead", 2 },
			{ "gunpowder", 1 },
			{ "scrap_metal", 1 },
		},
		itemWorth = 4,
		sound = "craft",
		spendTime = 10,
	},
	{
		id = "rpg7_ammo",
		item = { "rpg7_ammo", 1 },
		need = {
			{ "plastic_explosives", 4 },
			{ "steel", 1 },
			{ "provoloka", 2 },
			{ "glue_tag", 2 },
		},
		itemWorth = 60,
		sound = "craft",
		spendTime = 5,
	},
	{
		id = "titan",
		item = { "titan", 1 },
		need = {
			{ "titan_ore", 2 },
			{ "aluminium", 1 },
			{ "steel", 1 },
		},
		itemWorth = 30,
		sound = "blacksmith",
		spendTime = 10,
	},
	{
		itemWorth = 15,
		need = {
			{ "aluminium", 1 },
			{ "cable", 1 },
			{ "sulfuric_acid", 1 },
			{ "tape", 2 },
		},
		id = "capacitor",
		item = { "capacitor", 1 },
		spendTime = 10,
	},
	{
		itemWorth = 70,
		need = {
			{ "firebrick", 1 },
			{ "flint", 1 },
			{ "sulfuric_acid", 1 },
			{ "lead", 20 },
			{ "aluminium", 1 },
			{ "steel", 1 },
		},
		id = "armortile",
		item = { "armortile", 1 },
		spendTime = 10,
	},
	{
		itemWorth = 60,
		need = {
			{ "mushroom", 1 },
			{ "lymph", 5 },
			{ "bottled_water", 10 },
			{ "bone", 5 },
			{ "fat", 5 },
			{ "sulfur", 20 },
		},
		id = "growfast",
		item = { "growfast", 1 },
		spendTime = 10,
	},
	{
		itemWorth = 100,
		need = {
			{ "tape", 8 },
			{ "capacitor", 8 },
			{ "cable", 15 },
			{ "provoloka", 10 },
			{ "electronic_part", 8 },
			{ "batteryaaa", 8 },
		},
		id = "flashlight7",
		item = { "flashlight7", 1 },
		spendTime = 10,
	},
	{
		itemWorth = 65,
		need = {
			{ "wood", 5 },
			{ "glue_tag", 5 },
			{ "provoloka", 10 },
			{ "screw", 2 },
		},
		id = "fishing_rod2",
		item = { "fishing_rod2", 1 },
		spendTime = 10,
	},
	{
		itemWorth = 800,
		need = {
			{ "wax", 20 },
			{ "chitin", 5 },
			{ "glue_tag", 6 },
			{ "prepared_skin", 1 },
		},
		id = "chitin_torch",
		item = { "chitin_torch", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 200,
		need = {
			{ "wax", 6 },
			{ "lymph", 10 },
			{ "blood_mold", 2 },
			{ "poison", 2 },
			{ "alcohol", 1 },
		},
		id = "antidote",
		item = { "antidote", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 420,
		need = {
			{ "prepared_skin", 2 },
			{ "metal_plate", 6 },
			{ "bresent", 6 },
			{ "boiled_skin", 12 },
			{ "rags2", 16 },
			{ "string", 10 },
			{ "wood", 5 },
		},
		id = "bag3",
		item = { "bag3", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 1750,
		need = {
			{ "chitin", 100 },
			{ "bresent", 10 },
			{ "rubber", 20 },
			{ "copper", 8 },
			{ "prepared_skin", 10 },
			{ "rags2", 20 },
			{ "provoloka", 10 },
			{ "string", 60 },
		},
		id = "chitin_armor",
		item = { "chitin_armor", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 3500,
		need = {
			{ "titan", 70 },
			{ "prepared_skin", 50 },
			{ "copper", 10 },
			{ "bresent", 16 },
			{ "rubber", 20 },
		},
		id = "miner_armor",
		item = { "miner_armor", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 2550,
		need = {
			{ "armortile", 30 },
			{ "prepared_skin", 15 },
			{ "cable", 10 },
			{ "capacitor", 10 },
			{ "batteryaaa", 4 },
			{ "electronic_part", 20 },
			{ "rubber", 20 },
			{ "rubber_part", 10 },
		},
		id = "science_armor",
		item = { "science_armor", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 900,
		need = {
			{ "nettle", 40 },
			{ "fleawort", 20 },
			{ "dandelion", 30 },
			{ "rags2", 5 },
			{ "string", 5 },
			{ "metal_plate", 8 },
			{ "boiled_skin", 15 },
			{ "bresent", 20 },
		},
		id = "leshyi",
		item = { "leshyi", 1 },
		spendTime = 120,
	},
	{
		itemWorth = 1500,
		need = {
			{ "bresent", 10 },
			{ "rubber", 10 },
			{ "tape", 15 },
			{ "rags2", 10 },
			{ "string", 10 },
		},
		id = "ozk",
		item = { "ozk", 1 },
		spendTime = 120,
	},
	{
		id = "pm",
		item = { "pm", 1 },
		need = {
			{ "oil", 20 },
			{ "screw", 1 },
			{ "coil", 1 },
			{ "scrap_metal", 5 },
		},
		itemWorth = 20,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "nagant",
		item = { "nagant", 1 },
		need = {
			{ "oil", 80 },
			{ "screw", 4 },
			{ "coil", 2 },
			{ "weapons_parts", 4 },
			{ "wood", 1 },
			{ "scrap_metal", 15 },
		},
		itemWorth = 200,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "tt",
		item = { "tt", 1 },
		need = {
			{ "oil", 100 },
			{ "screw", 4 },
			{ "coil", 3 },
			{ "weapons_parts", 8 },
			{ "aluminium", 6 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 500,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "aps",
		item = { "aps", 1 },
		need = {
			{ "oil", 150 },
			{ "screw", 6 },
			{ "coil", 3 },
			{ "weapons_parts", 10 },
			{ "aluminium", 6 },
			{ "wood", 1 },
			{ "scrap_metal", 30 },
		},
		itemWorth = 600,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "armorpiercer",
		item = { "armorpiercer", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 5 },
			{ "coil", 5 },
			{ "weapons_parts", 12 },
			{ "aluminium", 10 },
			{ "steel", 6 },
			{ "scrap_metal", 40 },
		},
		itemWorth = 600,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "musket",
		item = { "musket", 1 },
		need = {
			{ "water_pipe", 2 },
			{ "glue_tag", 6 },
			{ "oil", 100 },
			{ "screw", 3 },
			{ "coil", 2 },
			{ "weapons_parts", 2 },
			{ "wood", 2 },
			{ "scrap_metal", 10 },
		},
		itemWorth = 60,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "mosin",
		item = { "mosin", 1 },
		need = {
			{ "oil", 160 },
			{ "screw", 5 },
			{ "coil", 3 },
			{ "weapons_parts", 8 },
			{ "aluminium", 10 },
			{ "wood", 2 },
			{ "scrap_metal", 15 },
		},
		itemWorth = 600,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "mosin_sniper",
		item = { "mosin_sniper", 1 },
		need = {
			{ "oil", 100 },
			{ "screw", 4 },
			{ "coil", 3 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "wood", 2 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 800,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "svt",
		item = { "svt", 1 },
		need = {
			{ "oil", 240 },
			{ "screw", 10 },
			{ "coil", 8 },
			{ "weapons_parts", 10 },
			{ "aluminium", 12 },
			{ "wood", 2 },
			{ "scrap_metal", 25 },
		},
		itemWorth = 1000,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "svd",
		item = { "svd", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 8 },
			{ "coil", 6 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "steel", 10 },
			{ "wood", 2 },
			{ "scrap_metal", 30 },
		},
		itemWorth = 1200,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "svu",
		item = { "svu", 1 },
		need = {
			{ "oil", 300 },
			{ "screw", 12 },
			{ "coil", 8 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "steel", 10 },
			{ "titan", 5 },
			{ "scrap_metal", 35 },
		},
		itemWorth = 1400,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "izh",
		item = { "izh", 1 },
		need = {
			{ "oil", 240 },
			{ "screw", 8 },
			{ "coil", 2 },
			{ "weapons_parts", 5 },
			{ "wood", 2 },
			{ "scrap_metal", 10 },
		},
		itemWorth = 400,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "toz",
		item = { "toz", 1 },
		need = {
			{ "oil", 300 },
			{ "screw", 12 },
			{ "coil", 8 },
			{ "weapons_parts", 15 },
			{ "aluminium", 15 },
			{ "wood", 2 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 600,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "saiga",
		item = { "saiga", 1 },
		need = {
			{ "oil", 300 },
			{ "screw", 8 },
			{ "coil", 5 },
			{ "weapons_parts", 15 },
			{ "aluminium", 10 },
			{ "steel", 15 },
			{ "wood", 2 },
			{ "scrap_metal", 30 },
		},
		itemWorth = 800,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "pepperbox",
		item = { "pepperbox", 1 },
		need = {
			{ "oil", 300 },
			{ "screw", 14 },
			{ "coil", 8 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "steel", 5 },
			{ "titan", 5 },
			{ "wood", 1 },
			{ "scrap_metal", 40 },
		},
		itemWorth = 1000,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "pps",
		item = { "pps", 1 },
		need = {
			{ "screw", 3 },
			{ "coil", 1 },
			{ "tape", 5 },
			{ "scrap_metal", 10 },
		},
		itemWorth = 100,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "ppsh",
		item = { "ppsh", 1 },
		need = {
			{ "oil", 30 },
			{ "screw", 3 },
			{ "coil", 2 },
			{ "weapons_parts", 3 },
			{ "wood", 2 },
			{ "scrap_metal", 15 },
		},
		itemWorth = 200,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "aks74u",
		item = { "aks74u", 1 },
		need = {
			{ "oil", 150 },
			{ "screw", 9 },
			{ "coil", 3 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "wood", 1 },
			{ "scrap_metal", 25 },
		},
		itemWorth = 400,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "ak74_single",
		item = { "ak74_single", 1 },
		need = {
			{ "oil", 220 },
			{ "screw", 9 },
			{ "coil", 6 },
			{ "weapons_parts", 10 },
			{ "aluminium", 15 },
			{ "wood", 2 },
			{ "scrap_metal", 30 },
		},
		itemWorth = 600,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "abakan",
		item = { "abakan", 1 },
		need = {
			{ "oil", 100 },
			{ "screw", 4 },
			{ "coil", 3 },
			{ "weapons_parts", 5 },
			{ "aluminium", 5 },
			{ "steel", 10 },
			{ "titan", 2 },
			{ "scrap_metal", 40 },
		},
		itemWorth = 1200,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "rpk74",
		item = { "rpk74", 1 },
		need = {
			{ "oil", 100 },
			{ "screw", 4 },
			{ "coil", 3 },
			{ "weapons_parts", 8 },
			{ "aluminium", 10 },
			{ "wood", 2 },
			{ "scrap_metal", 50 },
		},
		itemWorth = 500,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "dp",
		item = { "dp", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 5 },
			{ "coil", 5 },
			{ "weapons_parts", 10 },
			{ "aluminium", 10 },
			{ "steel", 5 },
			{ "wood", 1 },
			{ "scrap_metal", 100 },
		},
		itemWorth = 700,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "pk",
		item = { "pk", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 8 },
			{ "coil", 5 },
			{ "weapons_parts", 15 },
			{ "aluminium", 15 },
			{ "steel", 4 },
			{ "titan", 2 },
			{ "wood", 2 },
			{ "scrap_metal", 200 },
		},
		itemWorth = 900,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "mlp",
		item = { "mlp", 1 },
		need = {
			{ "iron", 120 },
			{ "aluminium", 14 },
			{ "glue_tag", 4 },
			{ "wood", 2 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 300,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "shashka",
		item = { "shashka", 1 },
		need = {
			{ "prepared_skin", 5 },
			{ "metal_plate", 5 },
			{ "aluminium", 30 },
			{ "wood", 1 },
			{ "scrap_metal", 5 },
			{ "glue_tag", 3 },
		},
		itemWorth = 500,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "chitin_spear",
		item = { "chitin_spear", 1 },
		need = {
			{ "chitin", 40 },
			{ "wax", 4 },
			{ "prepared_skin", 5 },
			{ "sulfuric_acid", 5 },
		},
		itemWorth = 1000,
		sound = "craft",
		spendTime = 120,
	},
	{
		id = "shock_mace",
		item = { "shock_mace", 1 },
		need = {
			{ "steel", 5 },
			{ "aluminium", 5 },
			{ "cable", 5 },
			{ "tape", 5 },
			{ "capacitor", 5 },
			{ "batteryaaa", 5 },
			{ "electronic_part", 5 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 750,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "rpg7",
		item = { "rpg7", 1 },
		need = {
			{ "weapons_parts", 2 },
			{ "aluminium", 2 },
			{ "steel", 2 },
			{ "wood", 1 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 100,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "f_1",
		item = { "f_1", 1 },
		need = {
			{ "screw", 1 },
			{ "gunpowder", 35 },
			{ "scrap_metal", 10 },
		},
		itemWorth = 50,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "flamethrower",
		item = { "flamethrower", 1 },
		need = {
			{ "moto_part", 5 },
			{ "aluminium", 5 },
			{ "weapons_parts", 10 },
			{ "screw", 4 },
			{ "coil", 3 },
			{ "oil", 100 },
			{ "wood", 2 },
			{ "scrap_metal", 20 },
		},
		itemWorth = 800,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "motorboat",
		item = { "motorboat", 1 },
		need = {
			{ "moto_part", 5 },
			{ "tape", 12 },
			{ "provoloka", 12 },
			{ "oil", 150 },
			{ "screw", 6 },
		},
		itemWorth = 140,
		sound = "carbuild",
		spendTime = 120,
	},
	{
		id = "classic_mobile",
		item = { "classic_mobile", 1 },
		need = {
			{ "auto_part", 10 },
			{ "tape", 10 },
			{ "provoloka", 10 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 8 },
			{ "spark_plug", 4 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "engine_gas", 1 },
		},
		itemWorth = 100,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "vaz2101",
		item = { "vaz2101", 1 },
		need = {
			{ "auto_part", 10 },
			{ "tape", 10 },
			{ "provoloka", 10 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 8 },
			{ "spark_plug", 4 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "engine_gas", 1 },
		},
		itemWorth = 180,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "gaz24",
		item = { "gaz24", 1 },
		need = {
			{ "auto_part", 12 },
			{ "provoloka", 14 },
			{ "oil", 640 },
			{ "tire", 4 },
			{ "screw", 8 },
			{ "spark_plug", 4 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "cable", 2 },
			{ "engine_gas", 1 },
		},
		itemWorth = 100,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "gaz24_black",
		item = { "gaz24_black", 1 },
		need = {
			{ "auto_part", 12 },
			{ "tape", 8 },
			{ "oil", 1200 },
			{ "tire", 4 },
			{ "screw", 10 },
			{ "spark_plug", 8 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "copper", 8 },
			{ "engine_gas", 1 },
		},
		itemWorth = 350,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "uaz",
		item = { "uaz", 1 },
		need = {
			{ "auto_part", 30 },
			{ "provoloka", 14 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 10 },
			{ "spark_plug", 4 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "cable", 8 },
			{ "engine_gas", 1 },
		},
		itemWorth = 300,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "uaz452",
		item = { "uaz452", 1 },
		need = {
			{ "auto_part", 30 },
			{ "provoloka", 14 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 10 },
			{ "spark_plug", 4 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "cable", 8 },
			{ "engine_gas", 1 },
		},
		itemWorth = 300,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "gaz66",
		item = { "gaz66", 1 },
		need = {
			{ "auto_part", 50 },
			{ "provoloka", 14 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 12 },
			{ "rubber_part", 7 },
			{ "accumulator", 1 },
			{ "cable", 12 },
			{ "engine_diesel", 1 },
		},
		itemWorth = 400,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "zil130",
		item = { "zil130", 1 },
		need = {
			{ "auto_part", 50 },
			{ "provoloka", 14 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 12 },
			{ "rubber_part", 7 },
			{ "accumulator", 1 },
			{ "cable", 12 },
			{ "engine_diesel", 1 },
		},
		itemWorth = 605,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "kamaz",
		item = { "kamaz", 1 },
		need = {
			{ "auto_part", 50 },
			{ "provoloka", 14 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 12 },
			{ "rubber_part", 7 },
			{ "accumulator", 1 },
			{ "cable", 12 },
			{ "engine_diesel", 1 },
		},
		itemWorth = 800,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "kraz255",
		item = { "kraz255", 1 },
		need = {
			{ "auto_part", 60 },
			{ "tape", 12 },
			{ "provoloka", 12 },
			{ "oil", 500 },
			{ "tire", 4 },
			{ "screw", 10 },
			{ "rubber_part", 10 },
			{ "accumulator", 1 },
			{ "cable", 20 },
			{ "engine_diesel", 1 },
		},
		itemWorth = 1000,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "bav485",
		item = { "bav485", 1 },
		need = {
			{ "auto_part", 50 },
			{ "tape", 10 },
			{ "provoloka", 12 },
			{ "oil", 500 },
			{ "tire", 6 },
			{ "screw", 10 },
			{ "rubber_part", 6 },
			{ "accumulator", 1 },
			{ "cable", 12 },
			{ "engine_diesel", 1 },
		},
		itemWorth = 200,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "mi8",
		item = { "mi8", 1 },
		need = {
			{ "auto_part", 60 },
			{ "tape", 15 },
			{ "provoloka", 15 },
			{ "oil", 500 },
			{ "screw", 10 },
			{ "rubber_part", 11 },
			{ "accumulator", 1 },
			{ "cable", 25 },
			{ "steel", 30 },
		},
		itemWorth = 1000,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "belaz",
		item = { "belaz", 1 },
		need = {
			{ "auto_part", 100 },
			{ "tape", 30 },
			{ "provoloka", 30 },
			{ "oil", 4000 },
			{ "tire", 16 },
			{ "screw", 50 },
			{ "rubber_part", 100 },
			{ "accumulator", 10 },
			{ "cable", 70 },
			{ "steel", 200 },
		},
		itemWorth = 72000,
		sound = "carbuild",
		spendTime = 120,
	},
	{
		id = "electro_mobile",
		item = { "electro_mobile", 1 },
		need = {
			{ "auto_part", 50 },
			{ "tape", 20 },
			{ "provoloka", 20 },
			{ "oil", 1000 },
			{ "tire", 4 },
			{ "screw", 20 },
			{ "accumulator", 4 },
			{ "cable", 50 },
			{ "electro_motor", 4 },
			{ "nuclear_battery", 1 },
		},
		itemWorth = 400,
		sound = "carbuild",
		spendTime = 60,
	},
	{
		id = "injector_green",
		item = { "injector_green", 1 },
		need = {
			{ "coil", 1 },
			{ "strawberry", 2 },
			{ "emba_biomass", 30 },
		},
		itemWorth = 15,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "injector_blue",
		item = { "injector_blue", 1 },
		need = {
			{ "coil", 1 },
			{ "teethgrass", 1 },
			{ "fleawort", 1 },
			{ "emba_biomass", 30 },
		},
		itemWorth = 20,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "injector_purple",
		item = { "injector_purple", 1 },
		need = {
			{ "coil", 1 },
			{ "amanita", 1 },
			{ "mushroom", 1 },
			{ "emba_biomass", 30 },
		},
		itemWorth = 20,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_machete",
		item = { "emba_machete", 1 },
		need = {
			{ "aluminium", 4 },
			{ "metal_plate", 2 },
			{ "wood", 2 },
			{ "scrap_metal", 10 },
			{ "emba_biomass", 50 },
		},
		itemWorth = 20,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "revolver_rifle",
		item = { "revolver_rifle", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 6 },
			{ "coil", 2 },
			{ "weapons_parts", 3 },
			{ "wood", 2 },
			{ "scrap_metal", 15 },
			{ "emba_biomass", 30 },
		},
		itemWorth = 500,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_pp",
		item = { "emba_pp", 1 },
		need = {
			{ "oil", 200 },
			{ "screw", 5 },
			{ "coil", 3 },
			{ "weapons_parts", 4 },
			{ "aluminium", 4 },
			{ "wood", 1 },
			{ "scrap_metal", 15 },
			{ "emba_biomass", 35 },
		},
		itemWorth = 75,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "cocktail_gerin",
		item = { "cocktail_gerin", 1 },
		need = {
			{ "gas", 1000 },
			{ "soap", 1 },
			{ "emba_biomass", 2 },
		},
		itemWorth = 10,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "vacuum_grenade",
		item = { "vacuum_grenade", 1 },
		need = {
			{ "provoloka", 1 },
			{ "screw", 1 },
			{ "scrap_metal", 20 },
			{ "emba_biomass", 5 },
		},
		itemWorth = 50,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "emba_robot",
		item = { "emba_robot", 1 },
		need = {
			{ "tape", 20 },
			{ "cable", 20 },
			{ "aluminium", 20 },
			{ "copper", 20 },
			{ "steel", 20 },
			{ "batteryaaa", 20 },
			{ "capacitor", 20 },
			{ "electronic_part", 20 },
			{ "titan", 20 },
			{ "emba_biomass", 1500 },
		},
		itemWorth = 50,
		sound = "craft",
		spendTime = 15,
	},
	{
		id = "emba_suit1",
		item = { "emba_suit1", 1 },
		need = {
			{ "emba_dcomp", 10 },
			{ "rubber", 10 },
			{ "boiled_skin", 10 },
			{ "provoloka", 10 },
			{ "scrap_metal", 15 },
		},
		itemWorth = 300,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_suit2",
		item = { "emba_suit2", 1 },
		need = {
			{ "emba_dcomp", 20 },
			{ "bresent", 10 },
			{ "cable", 10 },
			{ "rubber", 15 },
			{ "metal_plate", 15 },
		},
		itemWorth = 300,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_suit3",
		item = { "emba_suit3", 1 },
		need = {
			{ "emba_dcomp", 30 },
			{ "bresent", 20 },
			{ "prepared_skin", 20 },
			{ "cable", 10 },
			{ "rubber", 10 },
			{ "aluminium", 15 },
			{ "provoloka", 20 },
		},
		itemWorth = 400,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_extractor",
		item = { "emba_extractor", 1 },
		need = {
			{ "emba_dcomp", 10 },
			{ "coil", 2 },
			{ "screw", 4 },
		},
		itemWorth = 800,
		sound = "craft",
		spendTime = 60,
	},
	{
		id = "emba_herbicide",
		item = { "emba_herbicide", 1 },
		need = {
			{ "emba_dcomp", 1 },
			{ "sulfur", 40 },
			{ "gas", 3000 },
			{ "bone_glue", 5 },
			{ "oil", 40 },
		},
		itemWorth = 10,
		sound = "craft",
		spendTime = 60,
	},
}